<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Cesar Taconeli" />


<title>Executivos compartilhados</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Gian Lima</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="https://gianlima.github.io/">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    GLM 1-10
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Conteúdo de GLM</li>
    <li class="dropdown-header">Módulo 2 - Revisão de modelos lineares</li>
    <li>
      <a href="reacao_mod2.html">Reação química + tipos de embalagens (Modelo com erros normais)</a>
    </li>
    <li>
      <a href="venda_cos_mod2.html">Vendas de cosméticos (Modelo com erros normais)</a>
    </li>
    <li>
      <a href="min_qua_pon_mod3.html">Módulo 3 - Modelo linear com erros heterocedásticos</a>
    </li>
    <li class="dropdown-header">Módulo 6 - Estimação em modelos lineares generalizados</li>
    <li>
      <a href="estim_glm_mod6.html">Estimação em modelos lineares generalizados</a>
    </li>
    <li>
      <a href="sini_auto_mod6.html">Sinistros de Automóveis (Dados de contagens)</a>
    </li>
    <li>
      <a href="aval_qua_mod8.html">Módulo 8 - Análise de deviance</a>
    </li>
    <li>
      <a href="sel_var_mod9.html">Módulo 9 - Seleção de covariáveis</a>
    </li>
    <li>
      <a href="diag_mod10.html">Módulo 10 - Diagnóstico do ajuste de MLGs</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    GLM 11-15
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Módulo 11 - Regressão para dados binários</li>
    <li>
      <a href="besouro_mod11.html">Auditoria</a>
    </li>
    <li>
      <a href="besouro_mod11.html">Besouro da Farinha</a>
    </li>
    <li>
      <a href="estimacao_mod11.html">Estimação em MLG usando bootstrap</a>
    </li>
    <li>
      <a href="plebis_mod11.html">Plebiscito no Chile</a>
    </li>
    <li class="dropdown-header">Módulo 12 - Regressão para dados binários - predição</li>
    <li>
      <a href="credito_mod12.html">Análise de risco de crédito</a>
    </li>
    <li>
      <a href="base_mod12.html">Base de dados sobre spams</a>
    </li>
    <li class="dropdown-header">Módulo 13 - Regressão para dados de contagens</li>
    <li>
      <a href="queda_idoso_mod13.html">Quedas de idosos</a>
    </li>
    <li>
      <a href="cromo_mod13.html">Cromossomos anormais (Regressão Poisson com termo offset)</a>
    </li>
    <li class="dropdown-header">Módulo 14 - Regressão para dados de contagens com super dispersão</li>
    <li>
      <a href="super_disp_mod14.html">superdispersão (simulação)</a>
    </li>
    <li>
      <a href="exe_comp_mod14.html">Executivos compartilhados</a>
    </li>
    <li>
      <a href="Consulta_mod14.html">Número de consultas ao médico (Austrália)</a>
    </li>
    <li>
      <a href="ratos_mod14.html">Suplementação de ferro em ratos</a>
    </li>
    <li>
      <a href="cevada_mod14.html">Doença da cevada</a>
    </li>
    <li class="dropdown-header">Módulo 15 - Regressão para dados contínuos assimétricos</li>
    <li>
      <a href="turbina_mod15.html">Tempo de vida de turbinas de avião</a>
    </li>
    <li>
      <a href="tweedie_valor_sin_mod15.html">Valor de sinistros</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/gianlima/r-exams-tutorial">
    <span class="fa fa-github fa-lg"></span>
     
    GitHub
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Executivos compartilhados</h1>
<h4 class="author">Cesar Taconeli</h4>

</div>


<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">require</span>(car) </a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">require</span>(MASS)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw">require</span>(lme4)</a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="kw">require</span>(hnp)</a>
<a class="sourceLine" id="cb1-5" data-line-number="5"></a>
<a class="sourceLine" id="cb1-6" data-line-number="6"><span class="kw">help</span>(<span class="st">&quot;Ornstein&quot;</span>)</a>
<a class="sourceLine" id="cb1-7" data-line-number="7"><span class="kw">data</span>(Ornstein)</a>
<a class="sourceLine" id="cb1-8" data-line-number="8"><span class="kw">head</span>(Ornstein) </a></code></pre></div>
<pre><code>##   assets sector nation interlocks
## 1 147670    BNK    CAN         87
## 2 133000    BNK    CAN        107
## 3 113230    BNK    CAN         94
## 4  85418    BNK    CAN         48
## 5  75477    BNK    CAN         66
## 6  40742    FIN    CAN         69</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">summary</span>(Ornstein)</a></code></pre></div>
<pre><code>##      assets           sector   nation      interlocks    
##  Min.   :    62   MIN    :54   CAN:117   Min.   :  0.00  
##  1st Qu.:   519   MAN    :48   OTH: 18   1st Qu.:  3.00  
##  Median :  1397   AGR    :47   UK : 17   Median :  9.00  
##  Mean   :  5978   FIN    :22   US : 96   Mean   : 13.58  
##  3rd Qu.:  4326   MER    :20             3rd Qu.: 18.00  
##  Max.   :147670   WOD    :19             Max.   :107.00  
##                   (Other):38</code></pre>
<p>Variáveis: <strong>assets:</strong> ativos da corporação (em milhões de dolares);<br />
<strong>sector:</strong> setor de operação (AGR: agriculture; TRN: transportes; <strong>MIN:</strong> mineração, metais,…<br />
<strong>nation:</strong> CAN: Canadá; UK: Reino Unido; US: Estados Unidos; OTH: outro.<br />
<strong>interlocks:</strong> Número de diretores e executivos compartilhados com outras companhias.</p>
<p><strong>Objetivo: modelar interlocks em função das demais variáveis.</strong></p>
<div id="alguns-gráficos" class="section level2">
<h2>Alguns gráficos</h2>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw">boxplot</span>(Ornstein<span class="op">$</span>assets) </a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Distribuição dos ativos extremamente assimétrica, com algumas companhias bastante discrepantes (superiores, em relação aos ativos) em relação às demais.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw">boxplot</span>(<span class="kw">log</span>(Ornstein<span class="op">$</span>assets)) </a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Utilizar o logaritmo simetriza a distribuição dos ativos. Com base nisso, vamos usar <strong>log(assets)</strong> no modelo.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw">plot</span>(<span class="kw">log</span>(Ornstein<span class="op">$</span>assets),Ornstein<span class="op">$</span>interlocks,<span class="dt">pch=</span><span class="dv">20</span>,</a>
<a class="sourceLine" id="cb7-2" data-line-number="2">     <span class="dt">ylab=</span><span class="st">&#39;Número de diretores compartilhados&#39;</span>,<span class="dt">xlab=</span><span class="st">&#39;Ativos (em milhões de dolares)&#39;</span>)</a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="kw">boxplot</span>(Ornstein<span class="op">$</span>interlocks<span class="op">~</span>Ornstein<span class="op">$</span>nation,<span class="dt">xlab=</span><span class="st">&#39;País&#39;</span>,</a>
<a class="sourceLine" id="cb8-2" data-line-number="2">        <span class="dt">ylab=</span><span class="st">&#39;Número de diretores compartilhados&#39;</span>)</a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw">boxplot</span>(Ornstein<span class="op">$</span>interlocks<span class="op">~</span>Ornstein<span class="op">$</span>sector,<span class="dt">xlab=</span><span class="st">&#39;Setor&#39;</span>,</a>
<a class="sourceLine" id="cb9-2" data-line-number="2">        <span class="dt">ylab=</span><span class="st">&#39;Número de diretores compartilhados&#39;</span>)</a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-4-3.png" width="672" /></p>
</div>
<div id="ajuste-0---modelo-normal" class="section level2">
<h2>Ajuste 0 - Modelo Normal</h2>
<p>Vamos tentar um modelo com erros normais.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">ajuste0 &lt;-<span class="st"> </span><span class="kw">lm</span>(interlocks <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(assets) <span class="op">+</span><span class="st"> </span>nation <span class="op">+</span><span class="st"> </span>sector, <span class="dt">data=</span>Ornstein)</a>
<a class="sourceLine" id="cb10-2" data-line-number="2"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb10-3" data-line-number="3"><span class="kw">plot</span>(ajuste0) <span class="co"># Bah.</span></a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="ajuste-1---modelo-loglinear-poisson" class="section level2">
<h2>Ajuste 1 - Modelo loglinear Poisson</h2>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">ajuste1 &lt;-<span class="st"> </span><span class="kw">glm</span>(interlocks<span class="op">~</span><span class="kw">log</span>(assets)<span class="op">+</span>nation<span class="op">+</span>sector, <span class="dt">family=</span>poisson, <span class="dt">data=</span>Ornstein)</a>
<a class="sourceLine" id="cb11-2" data-line-number="2"><span class="kw">summary</span>(ajuste1) </a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = interlocks ~ log(assets) + nation + sector, family = poisson, 
##     data = Ornstein)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -6.7111  -2.3159  -0.4595   1.2824   6.2849  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.83938    0.13664  -6.143 8.09e-10 ***
## log(assets)  0.45145    0.01698  26.585  &lt; 2e-16 ***
## nationOTH   -0.10699    0.07438  -1.438 0.150301    
## nationUK    -0.38722    0.08951  -4.326 1.52e-05 ***
## nationUS    -0.77239    0.04963 -15.562  &lt; 2e-16 ***
## sectorBNK   -0.16651    0.09575  -1.739 0.082036 .  
## sectorCON   -0.48928    0.21320  -2.295 0.021736 *  
## sectorFIN   -0.11161    0.07571  -1.474 0.140457    
## sectorHLD   -0.01491    0.11924  -0.125 0.900508    
## sectorMAN    0.12187    0.07614   1.600 0.109489    
## sectorMER    0.06157    0.08670   0.710 0.477601    
## sectorMIN    0.24985    0.06888   3.627 0.000286 ***
## sectorTRN    0.15181    0.07893   1.923 0.054453 .  
## sectorWOD    0.49825    0.07560   6.590 4.39e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 3737.0  on 247  degrees of freedom
## Residual deviance: 1547.1  on 234  degrees of freedom
## AIC: 2473.1
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Repare que a deviance residual excede muito o respectivo número de graus de liberdade (1547&gt;&gt;&gt;234). Este é um <strong>indicativo de falta de ajuste.</strong></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb13-2" data-line-number="2"><span class="kw">plot</span>(ajuste1)</a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Atentem para a escala dos resíduos, com valores acima de 5 e abaixo de -5!!!</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="kw">hnp</span>(ajuste1) <span class="co"># Claramente o modelo não se ajusta aos dados.</span></a></code></pre></div>
<pre><code>## Poisson model</code></pre>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="parâmetro-de-dispersão" class="section level2">
<h2>Parâmetro de dispersão</h2>
<p>Estimando o parâmetro de dispersão com base na estatística X2 de Pearson:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">phi &lt;-<span class="st"> </span><span class="kw">sum</span>(<span class="kw">rstandard</span>(ajuste1, <span class="dt">type=</span><span class="st">&#39;pearson&#39;</span>)<span class="op">**</span><span class="dv">2</span>)<span class="op">/</span><span class="dv">234</span>; phi <span class="co"># Muito maior que 1.</span></a></code></pre></div>
<pre><code>## [1] 6.798396</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="kw">summary</span>(ajuste1, <span class="dt">dispersion =</span> phi)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = interlocks ~ log(assets) + nation + sector, family = poisson, 
##     data = Ornstein)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -6.7111  -2.3159  -0.4595   1.2824   6.2849  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.83938    0.35626  -2.356   0.0185 *  
## log(assets)  0.45145    0.04428  10.196  &lt; 2e-16 ***
## nationOTH   -0.10699    0.19394  -0.552   0.5812    
## nationUK    -0.38722    0.23338  -1.659   0.0971 .  
## nationUS    -0.77239    0.12941  -5.968  2.4e-09 ***
## sectorBNK   -0.16651    0.24966  -0.667   0.5048    
## sectorCON   -0.48928    0.55589  -0.880   0.3788    
## sectorFIN   -0.11161    0.19741  -0.565   0.5718    
## sectorHLD   -0.01491    0.31091  -0.048   0.9618    
## sectorMAN    0.12187    0.19853   0.614   0.5393    
## sectorMER    0.06157    0.22607   0.272   0.7853    
## sectorMIN    0.24985    0.17960   1.391   0.1642    
## sectorTRN    0.15181    0.20581   0.738   0.4608    
## sectorWOD    0.49825    0.19713   2.528   0.0115 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 6.798396)
## 
##     Null deviance: 3737.0  on 247  degrees of freedom
## Residual deviance: 1547.1  on 234  degrees of freedom
## AIC: 2473.1
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Perceba que os erros padrões estão corrigidos (multiplicados pela <span class="math inline">\(\sqrt{\phi}\)</span>).</p>
<p>Já corresponde aos resultados de um modelo quase poisson.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="kw">sqrt</span>(phi) <span class="co"># Os erros padrões ficam multiplicados por 2.607.</span></a></code></pre></div>
<pre><code>## [1] 2.607373</code></pre>
</div>
<div id="ajuste-2---modelo-binomial-negativa" class="section level2">
<h2>Ajuste 2 - Modelo Binomial negativa</h2>
<p>Como alternativa, vamos ajustar um modelo de regressão com mesma estrutura, mas distribuição binomial negativa.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1">ajuste2 &lt;-<span class="st"> </span><span class="kw">glm.nb</span>(interlocks <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(assets) <span class="op">+</span><span class="st"> </span>nation <span class="op">+</span><span class="st"> </span>sector, <span class="dt">data=</span>Ornstein)</a>
<a class="sourceLine" id="cb22-2" data-line-number="2"><span class="kw">summary</span>(ajuste2) </a></code></pre></div>
<pre><code>## 
## Call:
## glm.nb(formula = interlocks ~ log(assets) + nation + sector, 
##     data = Ornstein, init.theta = 1.639034209, link = log)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.8087  -0.9897  -0.1886   0.4301   2.4080  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.82535    0.37976  -2.173   0.0298 *  
## log(assets)  0.45618    0.05185   8.799  &lt; 2e-16 ***
## nationOTH   -0.10455    0.23004  -0.454   0.6495    
## nationUK    -0.38945    0.23575  -1.652   0.0985 .  
## nationUS    -0.78820    0.13201  -5.971 2.36e-09 ***
## sectorBNK   -0.40846    0.37726  -1.083   0.2789    
## sectorCON   -0.75698    0.45711  -1.656   0.0977 .  
## sectorFIN   -0.10346    0.25181  -0.411   0.6812    
## sectorHLD   -0.21103    0.34982  -0.603   0.5463    
## sectorMAN    0.07677    0.18601   0.413   0.6798    
## sectorMER    0.07761    0.23246   0.334   0.7385    
## sectorMIN    0.23988    0.18837   1.273   0.2029    
## sectorTRN    0.10133    0.24752   0.409   0.6823    
## sectorWOD    0.39084    0.23253   1.681   0.0928 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(1.639) family taken to be 1)
## 
##     Null deviance: 521.58  on 247  degrees of freedom
## Residual deviance: 296.52  on 234  degrees of freedom
## AIC: 1675.3
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  1.639 
##           Std. Err.:  0.192 
## 
##  2 x log-likelihood:  -1645.257</code></pre>
<p>Repare que o valor da deviance residual, nesse caso, é bem mais próximo do respectivo número de graus de liberdade.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb24-2" data-line-number="2"><span class="kw">plot</span>(ajuste2)</a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb25-2" data-line-number="2"><span class="kw">hnp</span>(ajuste2)</a></code></pre></div>
<pre><code>## Negative binomial model (using MASS package)</code></pre>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
</div>
<div id="comparação-modelos" class="section level2">
<h2>Comparação modelos</h2>
<p>Vamos comparar os modelos Poisson e binomial negativa por meio dos AICs:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1"><span class="kw">AIC</span>(ajuste1, ajuste2)</a></code></pre></div>
<pre><code>##         df      AIC
## ajuste1 14 2473.102
## ajuste2 15 1675.257</code></pre>
<p>O modelo com melhor ajuste (menor AIC) é o <strong>binomial negativo.</strong> Vamos seguir com ele.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1"><span class="kw">compareCoefs</span>(ajuste1, ajuste2)</a></code></pre></div>
<pre><code>## Calls:
## 1: glm(formula = interlocks ~ log(assets) + nation + sector, family = 
##   poisson, data = Ornstein)
## 2: glm.nb(formula = interlocks ~ log(assets) + nation + sector, data = 
##   Ornstein, init.theta = 1.639034209, link = log)
## 
##             Model 1 Model 2
## (Intercept)  -0.839  -0.825
## SE            0.137   0.380
##                            
## log(assets)  0.4514  0.4562
## SE           0.0170  0.0518
##                            
## nationOTH   -0.1070 -0.1045
## SE           0.0744  0.2300
##                            
## nationUK    -0.3872 -0.3894
## SE           0.0895  0.2357
##                            
## nationUS    -0.7724 -0.7882
## SE           0.0496  0.1320
##                            
## sectorBNK   -0.1665 -0.4085
## SE           0.0958  0.3773
##                            
## sectorCON    -0.489  -0.757
## SE            0.213   0.457
##                            
## sectorFIN   -0.1116 -0.1035
## SE           0.0757  0.2518
##                            
## sectorHLD   -0.0149 -0.2110
## SE           0.1192  0.3498
##                            
## sectorMAN    0.1219  0.0768
## SE           0.0761  0.1860
##                            
## sectorMER    0.0616  0.0776
## SE           0.0867  0.2325
##                            
## sectorMIN    0.2498  0.2399
## SE           0.0689  0.1884
##                            
## sectorTRN    0.1518  0.1013
## SE           0.0789  0.2475
##                            
## sectorWOD    0.4983  0.3908
## SE           0.0756  0.2325
## </code></pre>
</div>
<div id="erros-padrões" class="section level2">
<h2>Erros padrões</h2>
<p>Observe a diferença dos erros padrões produzidos pelos ajustes dos modelos Poisson e binomial negativo. Os erros produzidos pela Poisson estão subestimados.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1"><span class="kw">confint</span>(ajuste1)</a></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                    2.5 %      97.5 %
## (Intercept) -1.108508434 -0.57287676
## log(assets)  0.418217514  0.48478568
## nationOTH   -0.254554747  0.03710951
## nationUK    -0.566365221 -0.21525523
## nationUS    -0.870179363 -0.67559428
## sectorBNK   -0.354010813  0.02137266
## sectorCON   -0.933489962 -0.09406728
## sectorFIN   -0.259604188  0.03725116
## sectorHLD   -0.254585771  0.21343143
## sectorMAN   -0.027718678  0.27087687
## sectorMER   -0.109959569  0.23012202
## sectorMIN    0.115403223  0.38547023
## sectorTRN   -0.003165433  0.30635642
## sectorWOD    0.349651988  0.64614536</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1"><span class="kw">confint</span>(ajuste2)</a></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                   2.5 %      97.5 %
## (Intercept) -1.57345115 -0.07816512
## log(assets)  0.35372210  0.56005140
## nationOTH   -0.55543403  0.37449051
## nationUK    -0.83720228  0.08676612
## nationUS    -1.04218086 -0.53384772
## sectorBNK   -1.16565968  0.39066048
## sectorCON   -1.62097710  0.18292301
## sectorFIN   -0.59221831  0.39460298
## sectorHLD   -0.86401193  0.51798451
## sectorMAN   -0.28770113  0.44182697
## sectorMER   -0.37170403  0.54437543
## sectorMIN   -0.12641357  0.60429312
## sectorTRN   -0.37999614  0.60160690
## sectorWOD   -0.05717997  0.85862294</code></pre>
<p>Os intervalos de confiança baseados na Poisson são excessivamente precisos, comprometendo a taxa de cobertura.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1"><span class="kw">Anova</span>(ajuste2) </a></code></pre></div>
<pre><code>## Analysis of Deviance Table (Type II tests)
## 
## Response: interlocks
##             LR Chisq Df Pr(&gt;Chisq)    
## log(assets)   78.366  1  &lt; 2.2e-16 ***
## nation        38.030  3  2.786e-08 ***
## sector        12.026  9     0.2118    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Pelo resultado do teste, o efeito de setor é não significativo (quando o número de diretores é ajustado por país e ativos). Vamos eliminar essa variável do modelo.</p>
</div>
<div id="ajuste-3---modelo-binomial-negativa-sem-var.-sector" class="section level2">
<h2>Ajuste 3 - Modelo Binomial negativa sem var. “sector”</h2>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1">ajuste3=<span class="kw">update</span>(ajuste2, <span class="op">~</span>.<span class="op">-</span>sector)</a>
<a class="sourceLine" id="cb39-2" data-line-number="2"><span class="kw">summary</span>(ajuste3)</a></code></pre></div>
<pre><code>## 
## Call:
## glm.nb(formula = interlocks ~ log(assets) + nation, data = Ornstein, 
##     init.theta = 1.537032922, link = log)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.9616  -1.0596  -0.1868   0.4241   2.1976  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.55007    0.31546  -1.744   0.0812 .  
## log(assets)  0.42611    0.03898  10.930  &lt; 2e-16 ***
## nationOTH   -0.06947    0.21704  -0.320   0.7489    
## nationUK    -0.30001    0.23184  -1.294   0.1957    
## nationUS    -0.72060    0.12395  -5.814 6.11e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(1.537) family taken to be 1)
## 
##     Null deviance: 496.89  on 247  degrees of freedom
## Residual deviance: 295.52  on 243  degrees of freedom
## AIC: 1669
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  1.537 
##           Std. Err.:  0.176 
## 
##  2 x log-likelihood:  -1656.968</code></pre>
<p>O resumo do ajuste indica maior frequência de diretores de empresas norte-americanas em relação às canadenses (referência). Além disso, a frequência (média) de diretores aumenta conforme os ativos da empresa.</p>
<p>Vamos testar a igualdade da frequência média de diretores das empresas que não são norte-americanas.</p>
</div>
<div id="ajuste-4---modelo-binomial-negativa" class="section level2">
<h2>Ajuste 4 - Modelo Binomial negativa</h2>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1">Ornstein<span class="op">$</span>IndicaUSA &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="kw">ifelse</span>(Ornstein<span class="op">$</span>nation<span class="op">==</span><span class="st">&#39;US&#39;</span>,<span class="st">&#39;USA&#39;</span>,<span class="st">&#39;NãoUSA&#39;</span>)) </a>
<a class="sourceLine" id="cb41-2" data-line-number="2">ajuste4 &lt;-<span class="st"> </span><span class="kw">glm.nb</span>(interlocks <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(assets)<span class="op">+</span>IndicaUSA,Ornstein)</a></code></pre></div>
<p>Agora, vamos testar a restição imposta comparando os modelos 3 e 4.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1"><span class="kw">anova</span>(ajuste3, ajuste4) <span class="co"># A diferença de deviances não é significativa. </span></a></code></pre></div>
<pre><code>## Likelihood ratio tests of Negative Binomial Models
## 
## Response: interlocks
##                     Model    theta Resid. df    2 x log-lik.   Test    df
## 1 log(assets) + IndicaUSA 1.523329       245       -1658.593             
## 2    log(assets) + nation 1.537033       243       -1656.968 1 vs 2     2
##   LR stat.  Pr(Chi)
## 1                  
## 2 1.625682 0.443596</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1"><span class="kw">summary</span>(ajuste4)</a></code></pre></div>
<pre><code>## 
## Call:
## glm.nb(formula = interlocks ~ log(assets) + IndicaUSA, data = Ornstein, 
##     init.theta = 1.523329307, link = log)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.9387  -1.0369  -0.1637   0.4179   2.2142  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -0.63978    0.30517  -2.096    0.036 *  
## log(assets)   0.43300    0.03861  11.215  &lt; 2e-16 ***
## IndicaUSAUSA -0.68155    0.11777  -5.787 7.16e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(1.5233) family taken to be 1)
## 
##     Null deviance: 493.53  on 247  degrees of freedom
## Residual deviance: 295.35  on 245  degrees of freedom
## AIC: 1666.6
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  1.523 
##           Std. Err.:  0.174 
## 
##  2 x log-likelihood:  -1658.593</code></pre>
<p>A frequência de diretores compartilhados é inferior nos Estados Unidos em relação às demais localidades estudadas. Estima-se que o número médio de diretores compartilhados nos EUA seja aproximadamente a metade, em relação às demais localidades (exp(-0,68)).</p>
<p>Vamos ajustar um modelo por quasi-verossimilhança, definido pela função de ligação logaritmica e função de variância <span class="math inline">\(V(\mu)=\phi\mu.\)</span></p>
</div>
<div id="ajuste-6---modelo-quasi-verossimilhança" class="section level2">
<h2>Ajuste 6 - Modelo quasi-verossimilhança</h2>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1">ajuste6 &lt;-<span class="st"> </span><span class="kw">glm</span>(interlocks <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(assets)<span class="op">+</span>IndicaUSA,<span class="dt">family=</span><span class="kw">quasi</span>(<span class="dt">link=</span><span class="st">&#39;log&#39;</span>,<span class="dt">variance=</span><span class="st">&#39;mu&#39;</span>),Ornstein)</a>
<a class="sourceLine" id="cb46-2" data-line-number="2"><span class="kw">summary</span>(ajuste6)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = interlocks ~ log(assets) + IndicaUSA, family = quasi(link = &quot;log&quot;, 
##     variance = &quot;mu&quot;), data = Ornstein)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -6.9034  -2.3786  -0.4741   1.4291   6.8949  
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -0.53533    0.23987  -2.232   0.0265 *  
## log(assets)   0.41849    0.02686  15.581  &lt; 2e-16 ***
## IndicaUSAUSA -0.65209    0.11316  -5.763 2.48e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasi family taken to be 6.620681)
## 
##     Null deviance: 3737.0  on 247  degrees of freedom
## Residual deviance: 1659.9  on 245  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Vamos tentar extrair a logverossimilhança maximizada para esse modelo:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1"><span class="kw">logLik</span>(ajuste6) <span class="co"># Como não especificamos completamente uma distribuição paramétrica, não temos uma verossimilhança.</span></a></code></pre></div>
<pre><code>## &#39;log Lik.&#39; NA (df=3)</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" data-line-number="1"><span class="kw">Anova</span>(ajuste6) <span class="co"># Os testes de hipóteses baseiam-se na função quase-desvio </span></a></code></pre></div>
<pre><code>## Analysis of Deviance Table (Type II tests)
## 
## Response: interlocks
##             LR Chisq Df Pr(&gt;Chisq)    
## log(assets)  231.931  1  &lt; 2.2e-16 ***
## IndicaUSA     36.965  1  1.203e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>e na diferença entre funções quasi-desvio para modelos encaixados que, segundo McCullagh(1983), funciona como o teste da razão de verossimilhanças.</p>
</div>
<div id="ajuste-7---modelo-poisson" class="section level2">
<h2>Ajuste 7 - Modelo Poisson</h2>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1">ajuste7 &lt;-<span class="st"> </span><span class="kw">glm</span>(interlocks<span class="op">~</span><span class="kw">log</span>(assets)<span class="op">+</span>IndicaUSA,<span class="dt">family =</span> poisson,Ornstein)</a></code></pre></div>
<p>Modelo de poisson com preditor semelhante aos modelos binomial negativo e de quase-verossimilhança.</p>
</div>
<div id="ajuste-8---quasi-verossimilhança-com-função-de-variância-quadrática" class="section level2">
<h2>Ajuste 8 - Quasi-verossimilhança com função de variância quadrática</h2>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1">ajuste8 &lt;-<span class="st"> </span><span class="kw">glm</span>(interlocks <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(assets)<span class="op">+</span>IndicaUSA,<span class="dt">family=</span><span class="kw">quasi</span>(<span class="dt">link=</span><span class="st">&#39;log&#39;</span>,<span class="dt">variance=</span><span class="st">&#39;mu^2&#39;</span>),Ornstein) </a></code></pre></div>
<p>O ajuste8 também corresponde a um modelo de quase verossimilhança, mas com função de variância quadrática (v(mu) = phi*mu^2).</p>
<p>Vamos comparar os ajustes dos modelos com distribuição de Poisson, binomial nehativa e por quasi verossimilhança.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1"><span class="kw">compareCoefs</span>(ajuste7,ajuste4,ajuste6, ajuste8)</a></code></pre></div>
<pre><code>## Calls:
## 1: glm(formula = interlocks ~ log(assets) + IndicaUSA, family = 
##   poisson, data = Ornstein)
## 2: glm.nb(formula = interlocks ~ log(assets) + IndicaUSA, data = 
##   Ornstein, init.theta = 1.523329307, link = log)
## 3: glm(formula = interlocks ~ log(assets) + IndicaUSA, family = 
##   quasi(link = &quot;log&quot;, variance = &quot;mu&quot;), data = Ornstein)
## 4: glm(formula = interlocks ~ log(assets) + IndicaUSA, family = 
##   quasi(link = &quot;log&quot;, variance = &quot;mu^2&quot;), data = Ornstein)
## 
##              Model 1 Model 2 Model 3 Model 4
## (Intercept)  -0.5353 -0.6398 -0.5353 -0.6764
## SE            0.0932  0.3052  0.2399  0.2977
##                                             
## log(assets)   0.4185  0.4330  0.4185  0.4380
## SE            0.0104  0.0386  0.0269  0.0381
##                                             
## IndicaUSAUSA  -0.652  -0.682  -0.652  -0.689
## SE             0.044   0.118   0.113   0.113
## </code></pre>
<p>Gráficos de resíduos de Pearson vs valores ajustados para os modelos quasi-poisson (ajuste6) e Poisson (ajuste7). Repare na escala dos resíduos.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),<span class="dt">las=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb56-2" data-line-number="2"><span class="kw">plot</span>(<span class="kw">fitted</span>(ajuste6),<span class="kw">rstudent</span>(ajuste6,<span class="dt">type=</span><span class="st">&#39;pearson&#39;</span>),<span class="dt">xlab=</span><span class="st">&#39;Preditor ajustado&#39;</span>,</a>
<a class="sourceLine" id="cb56-3" data-line-number="3">     <span class="dt">ylab=</span><span class="st">&#39;Resíduo padronizado de Pearson&#39;</span>,<span class="dt">main=</span><span class="st">&#39;Modelo quasi Poisson&#39;</span>)</a>
<a class="sourceLine" id="cb56-4" data-line-number="4"><span class="kw">plot</span>(<span class="kw">fitted</span>(ajuste7),<span class="kw">rstudent</span>(ajuste7,<span class="dt">type=</span><span class="st">&#39;pearson&#39;</span>),<span class="dt">xlab=</span><span class="st">&#39;Preditor ajustado&#39;</span>,</a>
<a class="sourceLine" id="cb56-5" data-line-number="5">     <span class="dt">ylab=</span><span class="st">&#39;Resíduo padronizado de Pearson&#39;</span>,<span class="dt">main=</span><span class="st">&#39;Modelo Poisson&#39;</span>)</a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Um pouco mais de diagnóstico:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" data-line-number="1"><span class="kw">influenceIndexPlot</span>(ajuste7,<span class="dt">vars=</span><span class="kw">c</span>(<span class="st">&#39;Studentized&#39;</span>,<span class="st">&#39;Cook&#39;</span>,<span class="st">&#39;Hat&#39;</span>),<span class="dt">id.n=</span><span class="dv">3</span>)</a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1"><span class="kw">influenceIndexPlot</span>(ajuste6,<span class="dt">vars=</span><span class="kw">c</span>(<span class="st">&#39;Studentized&#39;</span>,<span class="st">&#39;Cook&#39;</span>,<span class="st">&#39;Hat&#39;</span>),<span class="dt">id.n=</span><span class="dv">3</span>)</a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-27-2.png" width="672" /></p>
<p>Pode-se observar menor, novamnet, redução na escala dos resíduos e valores consideravelmente menores para as distâncias de Cook para o ajuste6.</p>
<p>Vamos explorar o efeito da quantidade de ativos.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" data-line-number="1"><span class="kw">require</span>(effects)</a>
<a class="sourceLine" id="cb59-2" data-line-number="2"><span class="kw">plot</span>(<span class="kw">allEffects</span>(ajuste4), <span class="dt">type =</span> <span class="st">&#39;response&#39;</span>)</a></code></pre></div>
<p><img src="exe_comp_mod14_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>E se usarmos o modelo Poisson com estimação por Bootstrap?</p>
</div>
<div id="ajuste-boostrap" class="section level2">
<h2>Ajuste Boostrap</h2>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" data-line-number="1">ajusteboot &lt;-<span class="st"> </span><span class="kw">Boot</span>(ajuste7, <span class="dt">R=</span><span class="dv">999</span>)</a></code></pre></div>
<p>Observe que usando bootstrap (NÃO PARAMÉTRICO) também contornamos o problema da superdispersão, com erros padrões próximos aos obtidos usando quase verossimilhança e a distribuição binomial negativa.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" data-line-number="1"><span class="kw">confint</span>(ajusteboot) <span class="co"># Intervalos de confiança bootstrap.</span></a></code></pre></div>
<pre><code>## Bootstrap bca confidence intervals
## 
##                   2.5 %      97.5 %
## (Intercept)  -0.9722124 -0.02243248
## log(assets)   0.3625008  0.46612668
## IndicaUSAUSA -0.8939350 -0.45466283</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" data-line-number="1"><span class="kw">confint.default</span>(ajuste6) <span class="co"># Intervalos de confiança baseados no modelo de QL</span></a></code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## (Intercept)  -1.0054652 -0.06519063
## log(assets)   0.3658453  0.47112958
## IndicaUSAUSA -0.8738815 -0.43030087</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" data-line-number="1"><span class="kw">confint.default</span>(ajuste7) <span class="co"># Intervalos de confiança baseados no MLG Poisson</span></a></code></pre></div>
<pre><code>##                   2.5 %     97.5 %
## (Intercept)  -0.7180426 -0.3526133
## log(assets)   0.3980285  0.4389463
## IndicaUSAUSA -0.7382880 -0.5658944</code></pre>
<p>Os ICs baseados no MLG são incorretamete precisos, em relação aos demais. Ver estudo de simulação em arquivo a parte.</p>
<p>Agora, vamos ajustar o modelo quase poisson com estimação robusta dos erros padrões (estimador sanduíche). Para isso, vamos usar a biblioteca geepack.</p>
</div>
<div id="ajuste-9---modelo-quasi-poisson-com-estimação-robusta-dos-erros-padrões" class="section level2">
<h2>Ajuste 9 - Modelo quasi-poisson com estimação robusta dos erros padrões</h2>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" data-line-number="1"><span class="kw">require</span>(geepack)</a>
<a class="sourceLine" id="cb67-2" data-line-number="2">Ornstein<span class="op">$</span>Subj &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(Ornstein)</a>
<a class="sourceLine" id="cb67-3" data-line-number="3">ajuste9 &lt;-<span class="st"> </span><span class="kw">geeglm</span>(interlocks <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(assets) <span class="op">+</span><span class="st"> </span>IndicaUSA, <span class="dt">family =</span> <span class="st">&#39;poisson&#39;</span>, <span class="dt">id =</span> Subj, <span class="dt">data=</span>Ornstein)</a>
<a class="sourceLine" id="cb67-4" data-line-number="4"><span class="kw">summary</span>(ajuste9)</a></code></pre></div>
<pre><code>## 
## Call:
## geeglm(formula = interlocks ~ log(assets) + IndicaUSA, family = &quot;poisson&quot;, 
##     data = Ornstein, id = Subj)
## 
##  Coefficients:
##              Estimate  Std.err    Wald Pr(&gt;|W|)    
## (Intercept)  -0.53533  0.23760   5.076   0.0243 *  
## log(assets)   0.41849  0.02567 265.723  &lt; 2e-16 ***
## IndicaUSAUSA -0.65209  0.10561  38.123 6.64e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Estimated Scale Parameters:
##             Estimate Std.err
## (Intercept)    6.541  0.6662
## 
## Correlation: Structure = independenceNumber of clusters:   248   Maximum cluster size: 1</code></pre>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4,h5",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
