<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Cesar Taconeli" />


<title>Sinistros de Automóveis (Dados de contagens)</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Gian Lima</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="https://gianlima.github.io/">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    GLM 1-9
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Conteúdo de GLM</li>
    <li class="dropdown-header">Módulo 2 - Revisão de modelos lineares</li>
    <li>
      <a href="reacao_mod2.html">Reação química + tipos de embalagens (Modelo com erros normais)</a>
    </li>
    <li>
      <a href="venda_cos_mod2.html">Vendas de cosméticos (Modelo com erros normais)</a>
    </li>
    <li>
      <a href="min_qua_pon_mod3.html">Módulo 3 - Modelo linear com erros heterocedásticos</a>
    </li>
    <li class="dropdown-header">Módulo 6 - Estimação em modelos lineares generalizados</li>
    <li>
      <a href="estim_glm_mod6.html">Estimação em modelos lineares generalizados</a>
    </li>
    <li>
      <a href="sini_auto_mod6.html">Sinistros de Automóveis (Dados de contagens)</a>
    </li>
    <li>
      <a href="aval_qua_mod8.html">Módulo 8 - Análise de deviance</a>
    </li>
    <li>
      <a href="sel_var_mod9.html">Módulo 9 - Seleção de covariáveis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    GLM 10-15
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="diag_mod10.html">Módulo 10 - Diagnóstico do ajuste de MLGs</a>
    </li>
    <li class="dropdown-header">Módulo 11 - Regressão para dados binários</li>
    <li>
      <a href="besouro_mod11.html">Auditoria</a>
    </li>
    <li>
      <a href="besouro_mod11.html">Besouro da Farinha</a>
    </li>
    <li>
      <a href="estimacao_mod11.html">Estimação em MLG usando bootstrap</a>
    </li>
    <li>
      <a href="plebis_mod11.html">Plebiscito no Chile</a>
    </li>
    <li class="dropdown-header">Módulo 12 - Regressão para dados binários - predição</li>
    <li>
      <a href="credito_mod12.html">Análise de risco de crédito</a>
    </li>
    <li>
      <a href="base_mod12.html">Base de dados sobre spams</a>
    </li>
    <li class="dropdown-header">Módulo 13 - Regressão para dados de contagens</li>
    <li>
      <a href="queda_idoso_mod13.html">Quedas de idosos</a>
    </li>
    <li>
      <a href="cromo_mod13.html">Cromossomos anormais (Regressão Poisson com termo offset)</a>
    </li>
    <li class="dropdown-header">Módulo 14 - Regressão para dados de contagens com super dispersão</li>
    <li>
      <a href="super_disp_mod14.html">superdispersão (simulação)</a>
    </li>
    <li>
      <a href="exe_comp_mod14.html">Executivos compartilhados</a>
    </li>
    <li>
      <a href="Consulta_mod14.html">Número de consultas ao médico (Austrália)</a>
    </li>
    <li>
      <a href="ratos_mod14.html">Suplementação de ferro em ratos</a>
    </li>
    <li>
      <a href="cevada_mod14.html">Doença da cevada</a>
    </li>
    <li class="dropdown-header">Módulo 15 - Regressão para dados contínuos assimétricos</li>
    <li>
      <a href="turbina_mod15.html">Tempo de vida de turbinas de avião</a>
    </li>
    <li>
      <a href="tweedie_valor_sin_mod15.html">Valor de sinistros</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/gianlima/r-exams-tutorial">
    <span class="fa fa-github fa-lg"></span>
     
    GitHub
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Sinistros de Automóveis (Dados de contagens)</h1>
<h4 class="author">Cesar Taconeli</h4>

</div>


<p>Pacotes (possivelmente) utilizados</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">require</span>(rattle.data)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">require</span>(ggplot2)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw">require</span>(statmod)</a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="kw">require</span>(ISLR)</a>
<a class="sourceLine" id="cb1-5" data-line-number="5"><span class="kw">require</span>(car)</a>
<a class="sourceLine" id="cb1-6" data-line-number="6"><span class="kw">require</span>(hnp)</a>
<a class="sourceLine" id="cb1-7" data-line-number="7"><span class="kw">require</span>(pscl)</a>
<a class="sourceLine" id="cb1-8" data-line-number="8"><span class="kw">require</span>(coefplot)</a>
<a class="sourceLine" id="cb1-9" data-line-number="9"><span class="kw">require</span>(effects)</a>
<a class="sourceLine" id="cb1-10" data-line-number="10"><span class="kw">require</span>(sandwich)</a>
<a class="sourceLine" id="cb1-11" data-line-number="11"><span class="kw">require</span>(lmtest)</a></code></pre></div>
<div id="regressão-para-dados-de-contagens." class="section level2">
<h2>Regressão para dados de contagens.</h2>
<p>Informações referentes a 500 portadores de seguro de automóvel de uma particular seguradora. Foram filtrados apenas os segurados cujas apólices têm mais de cinco anos. As variáveis são as seguintes:</p>
<p>idade: idade do segurado (em anos);</p>
<p>sexo: Masc para masculino e Fem para feminino;</p>
<p>usop: uso principal do veículo. Cidade para uso urbano e Estrada para uso rodoviário;</p>
<p>anosest: escolaridade do segurado, em anos de estudo;</p>
<p>claims: número de sinistros produzidos pelo segurado nos últimos cinco anos.</p>
<p>O objetivo aqui é modelar a frequência de sinistros em função das demais covariáveis.</p>
</div>
<div id="importação-dos-dados-e-análise-descritiva." class="section level2">
<h2>Importação dos dados e análise descritiva.</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">dados &lt;-<span class="st"> </span><span class="kw">read.csv2</span>(<span class="st">&#39;sinistros.csv&#39;</span>)[,<span class="op">-</span><span class="dv">1</span>]</a>
<a class="sourceLine" id="cb2-2" data-line-number="2"><span class="co"># dados &lt;- read.csv2(&#39;sinistros.csv&#39;)[,-1]</span></a>
<a class="sourceLine" id="cb2-3" data-line-number="3"></a>
<a class="sourceLine" id="cb2-4" data-line-number="4"><span class="kw">head</span>(dados, <span class="dv">10</span>) <span class="co"># Dez primeiras linhas da base</span></a></code></pre></div>
<pre><code>##    idade sexo    usop anosest claims
## 1     41  Fem Estrada      10      3
## 2     39 Masc  Cidade      16      0
## 3     46 Masc Estrada       5      1
## 4     45  Fem  Cidade       9      0
## 5     41  Fem  Cidade      12      1
## 6     33 Masc Estrada       8      7
## 7     50 Masc Estrada       6      1
## 8     47 Masc Estrada       4      0
## 9     44 Masc Estrada      13      3
## 10    41 Masc Estrada      13      1</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="kw">summary</span>(dados) <span class="co"># Algumas descritivas dos dados</span></a></code></pre></div>
<pre><code>##      idade        sexo          usop        anosest         claims   
##  Min.   :16.0   Fem :191   Cidade :237   Min.   : 4.0   Min.   :0.0  
##  1st Qu.:35.0   Masc:309   Estrada:263   1st Qu.: 7.0   1st Qu.:1.0  
##  Median :40.0                            Median :10.0   Median :1.0  
##  Mean   :39.9                            Mean   :10.3   Mean   :1.7  
##  3rd Qu.:45.0                            3rd Qu.:13.0   3rd Qu.:2.0  
##  Max.   :61.0                            Max.   :17.0   Max.   :9.0</code></pre>
</div>
<div id="análise-descritiva" class="section level2">
<h2>Análise descritiva</h2>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">5</span>,<span class="fl">4.5</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">cex =</span> <span class="fl">1.4</span>)</a>
<a class="sourceLine" id="cb6-2" data-line-number="2"><span class="kw">plot</span>(<span class="kw">table</span>(dados<span class="op">$</span>claims), <span class="dt">col =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">xlab =</span> <span class="st">&#39;Número de sinistros&#39;</span>,</a>
<a class="sourceLine" id="cb6-3" data-line-number="3">     <span class="dt">ylab =</span> <span class="st">&#39;Frequência&#39;, xaxt = &#39;</span>n<span class="st">&#39;)</span></a>
<a class="sourceLine" id="cb6-4" data-line-number="4"><span class="st">axis(1, 0:9) </span></a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Distribuição de frequências para o número de sinistros.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">d1 &lt;-<span class="st"> </span><span class="kw">with</span>(dados, <span class="kw">data.frame</span>(<span class="kw">table</span>(sexo, <span class="kw">factor</span>(claims, <span class="dt">levels =</span> <span class="dv">0</span><span class="op">:</span><span class="dv">9</span>))))</a>
<a class="sourceLine" id="cb7-2" data-line-number="2"><span class="kw">names</span>(d1) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;sexo&quot;</span>,<span class="st">&quot;claims&quot;</span>,<span class="st">&quot;Freq&quot;</span>)</a>
<a class="sourceLine" id="cb7-3" data-line-number="3"><span class="kw">ggplot</span>(<span class="dt">data =</span> d1, <span class="kw">aes</span>(<span class="dt">x =</span> claims, <span class="dt">y =</span> Freq)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb7-4" data-line-number="4"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>sexo) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">18</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Frequência&quot;) + xlab(&#39;Número de sinistros&#39;)</span></a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">d2 &lt;-<span class="st"> </span><span class="kw">with</span>(dados, <span class="kw">data.frame</span>(<span class="kw">table</span>(usop, <span class="kw">factor</span>(claims, <span class="dt">levels =</span> <span class="dv">0</span><span class="op">:</span><span class="dv">9</span>))))</a>
<a class="sourceLine" id="cb8-2" data-line-number="2"><span class="kw">names</span>(d2) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;usop&quot;</span>,<span class="st">&quot;claims&quot;</span>,<span class="st">&quot;Freq&quot;</span>)</a>
<a class="sourceLine" id="cb8-3" data-line-number="3"><span class="kw">ggplot</span>(<span class="dt">data =</span> d2, <span class="kw">aes</span>(<span class="dt">x =</span> claims, <span class="dt">y =</span> Freq)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>)<span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-4" data-line-number="4"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>usop) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">18</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Frequência&quot;) + xlab(&#39;Número de sinistros&#39;)</span></a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> dados, <span class="kw">aes</span>(<span class="dt">x =</span> anosest, <span class="dt">y =</span> claims)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_jitter</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb9-2" data-line-number="2"><span class="st">  </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">18</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Número de sinistros&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&#39;Anos de estudo&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb9-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&#39;loess&#39;</span>)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-4-3.png" width="672" /></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> dados, <span class="kw">aes</span>(<span class="dt">x =</span> idade, <span class="dt">y =</span> claims)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_jitter</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb10-2" data-line-number="2"><span class="st">  </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">18</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Número de sinistros&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&#39;Idade&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb10-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&#39;loess&#39;</span>)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-4-4.png" width="672" /></p>
</div>
<div id="ajuste-de-um-modelo-linear-com-erros-normais" class="section level2">
<h2>Ajuste de um modelo linear com erros normais</h2>
<p>Vamos ajustar um modelo de regressão linear, com erros normais, para o número de sinistros.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">ajuste1 &lt;-<span class="st"> </span><span class="kw">lm</span>(claims <span class="op">~</span><span class="st"> </span>idade <span class="op">+</span><span class="st"> </span>sexo <span class="op">+</span><span class="st"> </span>usop <span class="op">+</span><span class="st"> </span>anosest, <span class="dt">data=</span>dados)</a>
<a class="sourceLine" id="cb11-2" data-line-number="2"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">cex =</span> <span class="fl">1.4</span>, <span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb11-3" data-line-number="3"><span class="kw">plot</span>(ajuste1)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Os resíduos são claramente heterocedásticos (variância aumenta conforme a média) e tem distribuição assimétrica. O modelo linear não se ajusta bem aos dados.</p>
</div>
<div id="ajuste-de-um-modelo-log-linear-com-resposta-poisson" class="section level2">
<h2>Ajuste de um modelo log-linear com resposta poisson</h2>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1">ajuste2 &lt;-<span class="st"> </span><span class="kw">glm</span>(claims <span class="op">~</span><span class="st"> </span>idade <span class="op">+</span><span class="st"> </span>sexo <span class="op">+</span><span class="st"> </span>usop <span class="op">+</span><span class="st"> </span>anosest, <span class="dt">family =</span> <span class="kw">poisson</span>(<span class="dt">link =</span> <span class="st">&#39;log&#39;</span>),</a>
<a class="sourceLine" id="cb12-2" data-line-number="2">               <span class="dt">data =</span> dados)</a>
<a class="sourceLine" id="cb12-3" data-line-number="3"><span class="kw">coefficients</span>(ajuste2) </a></code></pre></div>
<pre><code>## (Intercept)       idade    sexoMasc usopEstrada     anosest 
##    2.699698   -0.058708   -0.016386    0.257935   -0.004463</code></pre>
</div>
<div id="estimativas-dos-parâmetros-de-regressão." class="section level2">
<h2>Estimativas dos parâmetros de regressão.</h2>
<p>Vamos extrair mais alguns elementos produzidos pela função glm:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="kw">head</span>(<span class="kw">model.matrix</span>(ajuste2)) </a></code></pre></div>
<pre><code>##   (Intercept) idade sexoMasc usopEstrada anosest
## 1           1    41        0           1      10
## 2           1    39        1           0      16
## 3           1    46        1           1       5
## 4           1    45        0           0       9
## 5           1    41        0           0      12
## 6           1    33        1           1       8</code></pre>
<p>Matriz do modelo.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1"><span class="kw">head</span>(<span class="kw">fitted</span>(ajuste2), <span class="dt">n =</span> <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##      1      2      3      4      5      6      7      8      9     10 
## 1.6586 1.3803 1.2440 1.0178 1.2701 2.6331 0.9793 1.1783 1.3499 1.6099</code></pre>
<p>Valores ajustados pelo modelo, para os 500 indivíduos da base, na escala da resposta.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="kw">head</span>(<span class="kw">predict</span>(ajuste2), <span class="dt">n =</span> <span class="dv">10</span>) </a></code></pre></div>
<pre><code>##        1        2        3        4        5        6        7        8 
##  0.50595  0.32227  0.21834  0.01765  0.23909  0.96816 -0.02095  0.16410 
##        9       10 
##  0.30005  0.47618</code></pre>
<p>Valores ajustados pelo modelo, para os 500 indivíduos da base, na escala do preditor.</p>
<p>Recomendo acessar a documentação da função predict.glm para conferir as opções. Voltaremos a ela adiante.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1">ajuste2<span class="op">$</span>iter </a></code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>Foram necessárias cinco iterações até a convergência no processo de estimação.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="kw">head</span>(ajuste2<span class="op">$</span>weights, <span class="dt">n =</span> <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##      1      2      3      4      5      6      7      8      9     10 
## 1.6586 1.3803 1.2440 1.0178 1.2701 2.6331 0.9793 1.1783 1.3499 1.6099</code></pre>
<p>Esses são os pesos calculados na última iteração do algoritmo de estimação.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="kw">summary</span>(ajuste2) </a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = claims ~ idade + sexo + usop + anosest, family = poisson(link = &quot;log&quot;), 
##     data = dados)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -2.541  -1.035  -0.123   0.573   3.014  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  2.69970    0.21264   12.70  &lt; 2e-16 ***
## idade       -0.05871    0.00503  -11.68  &lt; 2e-16 ***
## sexoMasc    -0.01639    0.07779   -0.21  0.83317    
## usopEstrada  0.25794    0.07644    3.37  0.00074 ***
## anosest     -0.00446    0.00934   -0.48  0.63286    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 733.84  on 499  degrees of freedom
## Residual deviance: 581.53  on 495  degrees of freedom
## AIC: 1579
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Um resumo mais detalhado do modelo ajustado.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="kw">vcov</span>(ajuste2)</a></code></pre></div>
<pre><code>##             (Intercept)      idade   sexoMasc usopEstrada    anosest
## (Intercept)   0.0452144 -9.164e-04 -1.671e-03  -2.056e-03 -7.660e-04
## idade        -0.0009164  2.527e-05 -1.217e-05   1.444e-05 -2.134e-06
## sexoMasc     -0.0016713 -1.217e-05  6.052e-03  -2.384e-03 -2.796e-05
## usopEstrada  -0.0020562  1.444e-05 -2.384e-03   5.844e-03 -4.182e-05
## anosest      -0.0007660 -2.134e-06 -2.796e-05  -4.182e-05  8.729e-05</code></pre>
<p>matriz de variâncias e covariâncias estimada para os parâmetros de regressão.</p>
<p>Para fins disáticos, vamos estimar o parâmetro de dispersão. Primeiro usando a estatística X^2 de Pearson.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1">mu &lt;-<span class="st"> </span><span class="kw">fitted</span>(ajuste2)</a>
<a class="sourceLine" id="cb28-2" data-line-number="2">y &lt;-<span class="st"> </span>dados<span class="op">$</span>claims</a>
<a class="sourceLine" id="cb28-3" data-line-number="3">df &lt;-<span class="st"> </span>ajuste2<span class="op">$</span>df.residual</a>
<a class="sourceLine" id="cb28-4" data-line-number="4">phi &lt;-<span class="st"> </span><span class="kw">sum</span>(((y<span class="op">-</span>mu)<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span>mu)<span class="op">/</span>df</a>
<a class="sourceLine" id="cb28-5" data-line-number="5">phi</a></code></pre></div>
<pre><code>## [1] 1.043</code></pre>
<p>Agora usando a deviance.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1">dev &lt;-<span class="st"> </span>ajuste2<span class="op">$</span>deviance</a>
<a class="sourceLine" id="cb30-2" data-line-number="2">phi &lt;-<span class="st"> </span>dev<span class="op">/</span>df</a>
<a class="sourceLine" id="cb30-3" data-line-number="3">phi</a></code></pre></div>
<pre><code>## [1] 1.175</code></pre>
</div>
<div id="inferências-e-qualidade-do-ajuste." class="section level2">
<h2>Inferências e qualidade do ajuste.</h2>
<p>Teste da razão de verossimilhanças</p>
<p>Vamos testar algumas hipóteses usando o TRV. Vamos denotar por B_… os parâmetros (betas) do modelo.</p>
<p>Hipótese 1- H0: BsexoMasc = 0.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1">ajH0 &lt;-<span class="st"> </span><span class="kw">glm</span>(claims <span class="op">~</span><span class="st"> </span>idade <span class="op">+</span><span class="st"> </span>usop <span class="op">+</span><span class="st"> </span>anosest, <span class="dt">family =</span> <span class="kw">poisson</span>(<span class="dt">link =</span> <span class="st">&#39;log&#39;</span>),</a>
<a class="sourceLine" id="cb32-2" data-line-number="2">            <span class="dt">data =</span> dados)</a></code></pre></div>
<p>ou, de forma abreviada:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1">ajH0 &lt;-<span class="st"> </span><span class="kw">update</span>(ajuste2, claims <span class="op">~</span>.<span class="op">-</span>sexo)</a></code></pre></div>
<p>Na mão:</p>
<p>Vamos extrair as log-verossimilhanças maximizadas sob os dois modelos:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1">l0 &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">logLik</span>(ajH0)); l0</a></code></pre></div>
<pre><code>## [1] -784.3</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" data-line-number="1">l1 &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">logLik</span>(ajuste2)); l1</a></code></pre></div>
<pre><code>## [1] -784.3</code></pre>
<p>A estatística do teste da razão de verossimilhanças fica dada por:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1">Lambda &lt;-<span class="st"> </span><span class="dv">-2</span><span class="op">*</span>(l0<span class="op">-</span>l1); Lambda</a></code></pre></div>
<pre><code>## [1] 0.04432</code></pre>
<p>Como estamos testando um único parâmetro, a distribuição de referência para o teste é a qui-quadrado com um grau de liberdade. Vamos obter o valor crítico para um nível de significância de 5%:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1"><span class="kw">qchisq</span>(<span class="fl">0.05</span>, <span class="dt">df =</span> <span class="dv">1</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## [1] 3.841</code></pre>
<p>Como o valor da estatística do teste não excede o valor crítico, a hipótese nula (não efeito de sexo) não é rejeitada ao nível de significância de 5%. Vamos calcular o p-valor do teste.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1"><span class="kw">pchisq</span>(Lambda, <span class="dt">df =</span> <span class="dv">1</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## [1] 0.8333</code></pre>
<p>Usando a função anova:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1"><span class="kw">anova</span>(ajH0, ajuste2, <span class="dt">test =</span> <span class="st">&#39;Chisq&#39;</span>)</a></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: claims ~ idade + usop + anosest
## Model 2: claims ~ idade + sexo + usop + anosest
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
## 1       496        582                     
## 2       495        582  1   0.0443     0.83</code></pre>
<p>Exercício: Aplicar o teste da razão de verossimilhanças no teste da hipótese nula H0: B_sexoMasc = B_anosest = 0.</p>
<p>Teste de Wald.</p>
<p>O resultado do teste de Wald, para cada parâmetro, já é apresentado no summary do modelo. Vamos aplicar o método de Wald para testar a hipótese H0: B_sexoMasc = B_anosest = 0.</p>
<p>Na mão. Começamos extraindo estimativas pontuais e a parte da matriz de variâncias e covariâncias referentes aos dois parâmetros sob teste.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1">B0 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">coef</span>(ajuste2)[<span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">5</span>)]); B0</a></code></pre></div>
<pre><code>##           [,1]
## [1,] -0.016386
## [2,] -0.004463</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1">VarB0 &lt;-<span class="st"> </span><span class="kw">vcov</span>(ajuste2)[<span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">5</span>),<span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">5</span>)]; VarB0</a></code></pre></div>
<pre><code>##            sexoMasc    anosest
## sexoMasc  6.052e-03 -2.796e-05
## anosest  -2.796e-05  8.729e-05</code></pre>
<p>Agora, vamos calcular a estatística do teste de Wald:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" data-line-number="1">W &lt;-<span class="st"> </span><span class="kw">t</span>(B0) <span class="op">%*%</span><span class="st"> </span><span class="kw">solve</span>(VarB0) <span class="op">%*%</span><span class="st"> </span>B0</a>
<a class="sourceLine" id="cb50-2" data-line-number="2">W</a></code></pre></div>
<pre><code>##        [,1]
## [1,] 0.2807</code></pre>
<p>Como estamos testando dois parâmetro, a distribuição de referência para o teste é a qui-quadrado com dois graus de liberdade. Vamos obter o valor crítico para um nível de significância de 5%:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1"><span class="kw">qchisq</span>(<span class="fl">0.05</span>, <span class="dt">df =</span> <span class="dv">2</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## [1] 5.991</code></pre>
<p>Como o valor da estatística do teste não excede o valor crítico, a hipótese nula (não efeito de sexo e escolaridade) não é rejeitada ao nível de significância de 5%. Vamos calcular o p-valor do teste.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1"><span class="kw">pchisq</span>(W, <span class="dt">df =</span> <span class="dv">2</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>##       [,1]
## [1,] 0.869</code></pre>
<p>Agora, vamos usar a função waldtest do pacote lmtest:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" data-line-number="1">ajH0 &lt;-<span class="st"> </span><span class="kw">update</span>(ajuste2, claims <span class="op">~</span>.<span class="op">-</span>sexo <span class="op">-</span><span class="st"> </span>anosest)</a>
<a class="sourceLine" id="cb56-2" data-line-number="2"><span class="kw">waldtest</span>(ajH0, ajuste2, <span class="dt">test =</span> <span class="st">&#39;Chisq&#39;</span>)</a></code></pre></div>
<pre><code>## Wald test
## 
## Model 1: claims ~ idade + usop
## Model 2: claims ~ idade + sexo + usop + anosest
##   Res.Df Df Chisq Pr(&gt;Chisq)
## 1    497                    
## 2    495  2  0.28       0.87</code></pre>
<p>Exercício: Aplicar o método de Wald no teste da hipótese nula H0: B_sexoMasc = B_idade = 0.</p>
</div>
<div id="intervalos-de-confiança" class="section level2">
<h2>Intervalos de confiança</h2>
<p>Agora, intervalos de confiança. Começando pelo método de Wald. Vamos obter um intervalo de 95% de confiança para B_idade:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1">Bchap &lt;-<span class="st"> </span><span class="kw">coef</span>(ajuste2)[<span class="dv">2</span>]; Bchap</a></code></pre></div>
<pre><code>##    idade 
## -0.05871</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" data-line-number="1">VBchap &lt;-<span class="st"> </span><span class="kw">vcov</span>(ajuste2)[<span class="dv">2</span>,<span class="dv">2</span>]; VBchap</a></code></pre></div>
<pre><code>## [1] 2.527e-05</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" data-line-number="1">ICB_idade &lt;-<span class="st"> </span><span class="kw">c</span>(Bchap <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(VBchap), Bchap <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(VBchap))</a>
<a class="sourceLine" id="cb62-2" data-line-number="2">ICB_idade</a></code></pre></div>
<pre><code>##    idade    idade 
## -0.06856 -0.04885</code></pre>
<p>Como alternativa, podemos usar a função confint.default:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1"><span class="kw">confint.default</span>(ajuste2, <span class="dt">parm =</span> <span class="st">&quot;idade&quot;</span>, <span class="dt">level =</span> <span class="fl">0.95</span>)</a></code></pre></div>
<pre><code>##          2.5 %   97.5 %
## idade -0.06856 -0.04885</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" data-line-number="1"><span class="kw">confint.default</span>(ajuste2, <span class="dt">parm =</span> <span class="st">&quot;idade&quot;</span>, <span class="dt">level =</span> <span class="fl">0.99</span>)</a></code></pre></div>
<pre><code>##          0.5 %   99.5 %
## idade -0.07166 -0.04576</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" data-line-number="1"><span class="kw">confint.default</span>(ajuste2, <span class="dt">level =</span> <span class="fl">0.95</span>)</a></code></pre></div>
<pre><code>##                2.5 %   97.5 %
## (Intercept)  2.28294  3.11646
## idade       -0.06856 -0.04885
## sexoMasc    -0.16886  0.13609
## usopEstrada  0.10811  0.40776
## anosest     -0.02278  0.01385</code></pre>
<p>Se quisermos um IC(95%) para exp(B_idade), basta exponenciar os limites do IC obtido para B_idade:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" data-line-number="1"><span class="kw">exp</span>(ICB_idade)</a></code></pre></div>
<pre><code>##  idade  idade 
## 0.9337 0.9523</code></pre>
<p>Procedimento semelhante valeria para qualquer outra função monótona de B_idade.</p>
<p>Vamos ilustrar agora a construção do IC baseado no perfil da verossimilhança. Para isso, precisamos obter o valor da (log) verossimilhança maximizada para um grid de valores de</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" data-line-number="1">B_idade_grid &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="op">-</span><span class="fl">0.08</span>, <span class="fl">-0.035</span>, <span class="dt">length.out =</span> <span class="dv">20</span>)</a></code></pre></div>
<p>Agora, para cada valor de B_idade em B_idade_grid vamos ajustar novamente o glm, mas fixando B_idade. Para cada ajuste vamos extrair o valor da log-verossimilhança maximizada. Antes, vamos aplicar esse procedimento a um particular valor de B_idade, para fins ilustrativos. Tomemos B_idade=-0.05.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" data-line-number="1">ajuste &lt;-<span class="st"> </span><span class="kw">glm</span>(claims <span class="op">~</span><span class="st"> </span><span class="kw">offset</span>(<span class="op">-</span><span class="fl">0.05</span> <span class="op">*</span><span class="st"> </span>idade) <span class="op">+</span><span class="st"> </span>usop <span class="op">+</span><span class="st"> </span>anosest <span class="op">+</span><span class="st"> </span>sexo, <span class="dt">family =</span> <span class="kw">poisson</span>(<span class="dt">link =</span> <span class="st">&#39;log&#39;</span>),</a>
<a class="sourceLine" id="cb73-2" data-line-number="2">              <span class="dt">data =</span> dados)</a>
<a class="sourceLine" id="cb73-3" data-line-number="3"><span class="kw">logLik</span>(ajuste)</a></code></pre></div>
<pre><code>## &#39;log Lik.&#39; -785.8 (df=4)</code></pre>
<p>log-verossimilhança maximizada para B_idade=-0.05. Agora, vamos aplicar igual procedimento para o grid de valores de B_idade.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" data-line-number="1">vet_logLik &lt;-<span class="st"> </span><span class="kw">numeric</span>()</a>
<a class="sourceLine" id="cb75-2" data-line-number="2"><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(B_idade_grid)){</a>
<a class="sourceLine" id="cb75-3" data-line-number="3">  B_idade &lt;-<span class="st"> </span>B_idade_grid[i]</a>
<a class="sourceLine" id="cb75-4" data-line-number="4">  ajuste &lt;-<span class="st"> </span><span class="kw">glm</span>(claims <span class="op">~</span><span class="st"> </span><span class="kw">offset</span>(B_idade <span class="op">*</span><span class="st"> </span>idade) <span class="op">+</span><span class="st"> </span>usop <span class="op">+</span><span class="st"> </span>anosest <span class="op">+</span><span class="st"> </span>sexo, <span class="dt">family =</span> <span class="kw">poisson</span>(<span class="dt">link =</span> <span class="st">&#39;log&#39;</span>),</a>
<a class="sourceLine" id="cb75-5" data-line-number="5">                <span class="dt">data =</span> dados)</a>
<a class="sourceLine" id="cb75-6" data-line-number="6">  vet_logLik[i] &lt;-<span class="st"> </span><span class="kw">logLik</span>(ajuste)</a>
<a class="sourceLine" id="cb75-7" data-line-number="7">}</a></code></pre></div>
<p>O argumento offset() acrescenta o termo correspondente ao preditor do modelo sem um parâmetro a ser estimado. É a forma usada para fixar o valor de beta em cada componente de B_idade_grid.</p>
<p>Agora, vamos calcular a estatística do teste da razão de verossimilhanças para cada valor de B_idade_grid.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">cex =</span> <span class="fl">1.4</span>, <span class="dt">las =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb76-2" data-line-number="2"><span class="kw">plot</span>(B_idade_grid, vet_logLik, <span class="dt">type =</span> <span class="st">&#39;b&#39;</span>, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">xlav =</span> <span class="st">&#39;B_idade&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Log-verossimilhança&#39;</span>)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>Gráfico do perfil da log-verossimilhança.</p>
<p>O intervalo de confiança 95% baseado no perfil da verossimilhança irá conter todos os valores de B_idade0 tais que -2*[l(B_idade0) - l(B_idade_chap)] &lt; 3.84, em que l(B_idade0) é a log-verossimilhança maximizada fixando<br />
B_idade em B_idade0, l(B_idade_chap) é a log-verossimilhança maximizada não fixando qualquer particular valor para B_idade e 3.84 é o quantil 0.95 da distribuição qui-quadrado com um grau de liberdade.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">cex =</span> <span class="fl">1.4</span>, <span class="dt">las =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb77-2" data-line-number="2"><span class="kw">plot</span>(B_idade_grid, vet_logLik, <span class="dt">type =</span> <span class="st">&#39;b&#39;</span>, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">xlav =</span> <span class="st">&#39;B_idade&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Log-verossimilhança&#39;</span>)</a>
<a class="sourceLine" id="cb77-3" data-line-number="3"><span class="kw">abline</span>(<span class="dt">h =</span> <span class="kw">logLik</span>(ajuste2) <span class="op">-</span><span class="st"> </span><span class="fl">3.84</span><span class="op">/</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Podemos calcular o IC baseado no perfil da verossimilhança usando a função confint:</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" data-line-number="1"><span class="kw">confint</span>(ajuste2, <span class="dt">parm =</span> <span class="st">&quot;idade&quot;</span>, <span class="dt">level =</span> <span class="fl">0.95</span>)</a></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##    2.5 %   97.5 % 
## -0.06856 -0.04885</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" data-line-number="1"><span class="kw">confint</span>(ajuste2, <span class="dt">parm =</span> <span class="st">&quot;idade&quot;</span>, <span class="dt">level =</span> <span class="fl">0.99</span>)</a></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##    0.5 %   99.5 % 
## -0.07165 -0.04575</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" data-line-number="1"><span class="kw">confint</span>(ajuste2)</a></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                2.5 %   97.5 %
## (Intercept)  2.28162  3.11524
## idade       -0.06856 -0.04885
## sexoMasc    -0.16817  0.13686
## usopEstrada  0.10862  0.40834
## anosest     -0.02280  0.01383</code></pre>
<p>Agora, para fins ilustrativos, vamos plotar os limites de confiança sobre o gráfico.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">cex =</span> <span class="fl">1.4</span>, <span class="dt">las =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb87-2" data-line-number="2"><span class="kw">plot</span>(B_idade_grid, vet_logLik, <span class="dt">type =</span> <span class="st">&#39;b&#39;</span>, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">xlav =</span> <span class="st">&#39;B_idade&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Log-verossimilhança&#39;</span>)</a>
<a class="sourceLine" id="cb87-3" data-line-number="3"><span class="kw">abline</span>(<span class="dt">h =</span> <span class="kw">logLik</span>(ajuste2) <span class="op">-</span><span class="st"> </span><span class="fl">3.84</span><span class="op">/</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb87-4" data-line-number="4"><span class="kw">abline</span>(<span class="dt">v =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.06855816</span>, <span class="fl">-0.04885103</span>), <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&#39;red&#39;</span>)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>Exercício: Construir o gráfico do perfil da verossimilhança e obter o IC(95%) para B_sexoM.</p>
<p>Gráficos de efeitos</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" data-line-number="1"><span class="kw">plot</span>(<span class="kw">allEffects</span>(ajuste2)) <span class="co"># Escala do link.</span></a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" data-line-number="1"><span class="kw">plot</span>(<span class="kw">allEffects</span>(ajuste2), <span class="dt">type =</span> <span class="st">&#39;response&#39;</span>) <span class="co"># Escala da resposta.</span></a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-38-2.png" width="672" /></p>
</div>
<div id="predições" class="section level2">
<h2>Predições</h2>
<p>Agora, vamos estimar o número médio de sinistros para alguns perfis de segurados. Primeiro, para segurados de 30 anos que fazem uso principal na estrada, sexo masculino e 10 anos de estudo.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" data-line-number="1">x0 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">30</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">10</span>))</a></code></pre></div>
<p>x0 Vetor de covariáveis. o primeiro termo corresponde ao intercepto.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb91-1" data-line-number="1">betas &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">coef</span>(ajuste2))</a>
<a class="sourceLine" id="cb91-2" data-line-number="2">betas</a></code></pre></div>
<pre><code>##           [,1]
## [1,]  2.699698
## [2,] -0.058708
## [3,] -0.016386
## [4,]  0.257935
## [5,] -0.004463</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb93-1" data-line-number="1"><span class="kw">t</span>(x0) <span class="op">%*%</span><span class="st"> </span>betas <span class="co"># Estimativa na escala do preditor (log(mu)).</span></a></code></pre></div>
<pre><code>##       [,1]
## [1,] 1.135</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" data-line-number="1"><span class="kw">exp</span>(<span class="kw">t</span>(x0) <span class="op">%*%</span><span class="st"> </span>betas)</a></code></pre></div>
<pre><code>##       [,1]
## [1,] 3.112</code></pre>
<p>Estimativa na escala da média. Assim, para o perfil de segurado considerado, estima-se, em média, 3.11 sinistros.</p>
<p>Agora, vamos usar a função predict.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb97-1" data-line-number="1"><span class="kw">predict</span>(ajuste2, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">idade =</span> <span class="dv">30</span>, <span class="dt">usop =</span> <span class="st">&#39;Estrada&#39;</span>, </a>
<a class="sourceLine" id="cb97-2" data-line-number="2">                                      <span class="dt">sexo =</span> <span class="st">&#39;Masc&#39;</span>, <span class="dt">anosest =</span> <span class="dv">10</span>))</a></code></pre></div>
<pre><code>##     1 
## 1.135</code></pre>
<p>Por default, o R retorna a predição na escala do link. Para obter a estimativa da média devemos aplicar a inversa da função de ligação:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb99-1" data-line-number="1"><span class="kw">predict</span>(ajuste2, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">idade =</span> <span class="dv">30</span>, <span class="dt">usop =</span> <span class="st">&#39;Estrada&#39;</span>, <span class="dt">sexo =</span> <span class="st">&#39;Masc&#39;</span>, </a>
<a class="sourceLine" id="cb99-2" data-line-number="2">                                      <span class="dt">anosest =</span> <span class="dv">10</span>), <span class="dt">type =</span> <span class="st">&#39;response&#39;</span>)</a></code></pre></div>
<pre><code>##     1 
## 3.112</code></pre>
<p>Agora, na escala da média, ou da resposta.</p>
<p>Podemos realizar predições para toda uma base de novos indivíduos. Uma pequena ilustração:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb101-1" data-line-number="1">dpred &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">idade =</span> <span class="kw">c</span>(<span class="dv">30</span>,<span class="dv">30</span>,<span class="dv">60</span>,<span class="dv">60</span>),</a>
<a class="sourceLine" id="cb101-2" data-line-number="2">                    <span class="dt">usop =</span> <span class="kw">c</span>(<span class="st">&#39;Estrada&#39;</span>,<span class="st">&#39;Cidade&#39;</span>,<span class="st">&#39;Estrada&#39;</span>,<span class="st">&#39;Cidade&#39;</span>),</a>
<a class="sourceLine" id="cb101-3" data-line-number="3">                    <span class="dt">sexo =</span> <span class="kw">c</span>(<span class="st">&#39;Masc&#39;</span>, <span class="st">&#39;Fem&#39;</span>, <span class="st">&#39;Fem&#39;</span>, <span class="st">&#39;Masc&#39;</span>),</a>
<a class="sourceLine" id="cb101-4" data-line-number="4">                    <span class="dt">anosest =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">12</span>, <span class="dv">15</span>))</a>
<a class="sourceLine" id="cb101-5" data-line-number="5"></a>
<a class="sourceLine" id="cb101-6" data-line-number="6">mu_est &lt;-<span class="st"> </span><span class="kw">predict</span>(ajuste2, <span class="dt">newdata =</span> dpred, <span class="dt">type =</span> <span class="st">&#39;response&#39;</span>)</a>
<a class="sourceLine" id="cb101-7" data-line-number="7">dpred<span class="op">$</span>mu &lt;-<span class="st"> </span>mu_est</a>
<a class="sourceLine" id="cb101-8" data-line-number="8"><span class="kw">rownames</span>(dpred) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;Perfil 1&#39;</span>, <span class="st">&#39;Perfil 2&#39;</span>, <span class="st">&#39;Perfil 3&#39;</span>, <span class="st">&#39;Perfil 4&#39;</span>)</a>
<a class="sourceLine" id="cb101-9" data-line-number="9">dpred</a></code></pre></div>
<pre><code>##          idade    usop sexo anosest     mu
## Perfil 1    30 Estrada Masc       5 3.1825
## Perfil 2    30  Cidade  Fem       7 2.4774
## Perfil 3    60 Estrada  Fem      12 0.5388
## Perfil 4    60  Cidade Masc      15 0.4041</code></pre>
<p>Estimativas para o número esperado de sinistros em cinco anos para os quatro perfis de segurados.</p>
<p>Vamos ver a distribuição de probabilidades estimada para cada perfil. Primeiro, vamos calcular as probabilidades ajustadas, usando as médias estimadas para cada perfil.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb103-1" data-line-number="1">Perfil1 &lt;-<span class="st"> </span><span class="kw">dpois</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">10</span>, mu_est[<span class="dv">1</span>])</a>
<a class="sourceLine" id="cb103-2" data-line-number="2">Perfil2 &lt;-<span class="st"> </span><span class="kw">dpois</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">10</span>, mu_est[<span class="dv">2</span>])</a>
<a class="sourceLine" id="cb103-3" data-line-number="3">Perfil3 &lt;-<span class="st"> </span><span class="kw">dpois</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">10</span>, mu_est[<span class="dv">3</span>])</a>
<a class="sourceLine" id="cb103-4" data-line-number="4">Perfil4 &lt;-<span class="st"> </span><span class="kw">dpois</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">10</span>, mu_est[<span class="dv">4</span>])</a></code></pre></div>
<p>Agora vamos plotar as probabilidades para avaliar as distribuições.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">cex =</span> <span class="fl">1.3</span>, <span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">las =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb104-2" data-line-number="2"><span class="kw">plot</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">10</span>, Perfil1, <span class="dt">type =</span> <span class="st">&#39;h&#39;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">xlab =</span> <span class="st">&#39;x&#39;</span>, <span class="dt">main =</span> <span class="st">&#39;Perfil 1&#39;</span>, </a>
<a class="sourceLine" id="cb104-3" data-line-number="3">     <span class="dt">xaxt =</span> <span class="st">&#39;n&#39;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.7</span>))</a>
<a class="sourceLine" id="cb104-4" data-line-number="4"><span class="kw">axis</span>(<span class="dv">1</span>, <span class="dv">0</span><span class="op">:</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb104-5" data-line-number="5"><span class="kw">plot</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">10</span>, Perfil2, <span class="dt">type =</span> <span class="st">&#39;h&#39;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">xlab =</span> <span class="st">&#39;x&#39;</span>, <span class="dt">main =</span> <span class="st">&#39;Perfil 2&#39;</span>, </a>
<a class="sourceLine" id="cb104-6" data-line-number="6">     <span class="dt">xaxt =</span> <span class="st">&#39;n&#39;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.7</span>))</a>
<a class="sourceLine" id="cb104-7" data-line-number="7"><span class="kw">axis</span>(<span class="dv">1</span>, <span class="dv">0</span><span class="op">:</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb104-8" data-line-number="8"><span class="kw">plot</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">10</span>, Perfil3, <span class="dt">type =</span> <span class="st">&#39;h&#39;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">xlab =</span> <span class="st">&#39;x&#39;</span>, <span class="dt">main =</span> <span class="st">&#39;Perfil 3&#39;</span>, </a>
<a class="sourceLine" id="cb104-9" data-line-number="9">     <span class="dt">xaxt =</span> <span class="st">&#39;n&#39;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.7</span>))</a>
<a class="sourceLine" id="cb104-10" data-line-number="10"><span class="kw">axis</span>(<span class="dv">1</span>, <span class="dv">0</span><span class="op">:</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb104-11" data-line-number="11"><span class="kw">plot</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">10</span>, Perfil4, <span class="dt">type =</span> <span class="st">&#39;h&#39;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">xlab =</span> <span class="st">&#39;x&#39;</span>, <span class="dt">main =</span> <span class="st">&#39;Perfil 4&#39;</span>, </a>
<a class="sourceLine" id="cb104-12" data-line-number="12">     <span class="dt">xaxt =</span> <span class="st">&#39;n&#39;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.7</span>))</a>
<a class="sourceLine" id="cb104-13" data-line-number="13"><span class="kw">axis</span>(<span class="dv">1</span>, <span class="dv">0</span><span class="op">:</span><span class="dv">10</span>)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>Intervalos de confiança para predições. Vamos considerar, novamente, de 30 anos que fazem uso principal na estrada, sexo masculino e 10 anos de estudo.</p>
<p>Primeiro na unha.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" data-line-number="1">x0 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">30</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">10</span>)) <span class="co"># Vetor de covariáveis.</span></a>
<a class="sourceLine" id="cb105-2" data-line-number="2"><span class="co"># Intercepto, idade, indicadora de uso na estrada e produto (idade*uso).  </span></a>
<a class="sourceLine" id="cb105-3" data-line-number="3"></a>
<a class="sourceLine" id="cb105-4" data-line-number="4">betaChap &lt;-<span class="st"> </span><span class="kw">coef</span>(ajuste2)</a>
<a class="sourceLine" id="cb105-5" data-line-number="5"><span class="co">#  Vetor de estimativas dos parâmetros de regressão.</span></a>
<a class="sourceLine" id="cb105-6" data-line-number="6"></a>
<a class="sourceLine" id="cb105-7" data-line-number="7">etaChap &lt;-<span class="st"> </span><span class="kw">crossprod</span>(x0, betaChap)</a>
<a class="sourceLine" id="cb105-8" data-line-number="8"><span class="co"># Predição na escala do preditor.</span></a>
<a class="sourceLine" id="cb105-9" data-line-number="9"></a>
<a class="sourceLine" id="cb105-10" data-line-number="10">varChap &lt;-<span class="st"> </span><span class="kw">vcov</span>(ajuste2)</a>
<a class="sourceLine" id="cb105-11" data-line-number="11"><span class="co"># Matriz de variâncias e covariâncias estimada para os estimadores dos parâmetros de regressão.</span></a>
<a class="sourceLine" id="cb105-12" data-line-number="12"></a>
<a class="sourceLine" id="cb105-13" data-line-number="13">VarEtaChap &lt;-<span class="st"> </span><span class="kw">t</span>(x0) <span class="op">%*%</span><span class="st"> </span>varChap <span class="op">%*%</span><span class="st"> </span>x0 </a>
<a class="sourceLine" id="cb105-14" data-line-number="14"><span class="co"># Erro padrão de etaChap.</span></a>
<a class="sourceLine" id="cb105-15" data-line-number="15"></a>
<a class="sourceLine" id="cb105-16" data-line-number="16"><span class="kw">c</span>(etaChap <span class="fl">-1.96</span> <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(VarEtaChap), etaChap <span class="fl">+1.96</span> <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(VarEtaChap))</a></code></pre></div>
<pre><code>## [1] 1.019 1.252</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" data-line-number="1"><span class="co"># IC 95% (na escala do preditor)</span></a>
<a class="sourceLine" id="cb107-2" data-line-number="2"></a>
<a class="sourceLine" id="cb107-3" data-line-number="3"><span class="kw">exp</span>(<span class="kw">c</span>(etaChap <span class="fl">-1.96</span> <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(VarEtaChap), etaChap <span class="fl">+1.96</span> <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(VarEtaChap))) </a></code></pre></div>
<pre><code>## [1] 2.771 3.496</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" data-line-number="1"><span class="co"># IC 95% (na escala da resposta)</span></a></code></pre></div>
<p>Agora, usando a função predict.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb110-1" data-line-number="1">pred_link &lt;-<span class="st"> </span><span class="kw">predict</span>(ajuste2, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">idade =</span> <span class="dv">30</span>, <span class="dt">usop =</span> <span class="st">&#39;Estrada&#39;</span>, <span class="dt">sexo =</span> <span class="st">&#39;Masc&#39;</span>, </a>
<a class="sourceLine" id="cb110-2" data-line-number="2">                                                   <span class="dt">anosest =</span> <span class="dv">10</span>), <span class="dt">se.fit =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p>Declarando se.fit = TRUE, a função retorna também o erro padrão de predição. pred_link</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" data-line-number="1">pred_link<span class="op">$</span>fit <span class="op">+</span><span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="fl">1.96</span>, <span class="fl">1.96</span>) <span class="op">*</span><span class="st"> </span>pred_link<span class="op">$</span>se.fit</a></code></pre></div>
<pre><code>## [1] 1.019 1.252</code></pre>
<p>IC 95% (na escala do preditor)</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" data-line-number="1"><span class="kw">exp</span>(pred_link<span class="op">$</span>fit <span class="op">+</span><span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="fl">1.96</span>, <span class="fl">1.96</span>) <span class="op">*</span><span class="st"> </span>pred_link<span class="op">$</span>se.fit)</a></code></pre></div>
<pre><code>## [1] 2.771 3.496</code></pre>
<p>IC 95% (na escala da resposta)</p>
<p>Agora, vamos obter intervalos de confiança para a frequência média de sinistros no atacado, considerando todos os vetores de covariáveis correspondentes aos 500 indivíduos da base.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb115-1" data-line-number="1">pred_base &lt;-<span class="st"> </span><span class="kw">predict</span>(ajuste2, <span class="dt">type =</span> <span class="st">&#39;link&#39;</span>, <span class="dt">se.fit =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb115-2" data-line-number="2">ic &lt;-<span class="st"> </span><span class="kw">cbind</span>(pred_base<span class="op">$</span>fit <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>pred_base<span class="op">$</span>se.fit, pred_base<span class="op">$</span>fit <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>pred_base<span class="op">$</span>se.fit)</a>
<a class="sourceLine" id="cb115-3" data-line-number="3">dados_inter &lt;-<span class="st"> </span><span class="kw">data.frame</span>(dados[,<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>], <span class="kw">exp</span>(pred_base<span class="op">$</span>fit), <span class="kw">exp</span>(ic))</a>
<a class="sourceLine" id="cb115-4" data-line-number="4"><span class="kw">head</span>(dados_inter, <span class="dt">n =</span> <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##    idade sexo    usop anosest exp.pred_base.fit.     X1    X2
## 1     41  Fem Estrada      10             1.6586 1.4197 1.938
## 2     39 Masc  Cidade      16             1.3803 1.1556 1.649
## 3     46 Masc Estrada       5             1.2440 1.0545 1.468
## 4     45  Fem  Cidade       9             1.0178 0.8804 1.177
## 5     41  Fem  Cidade      12             1.2701 1.1113 1.452
## 6     33 Masc Estrada       8             2.6331 2.3582 2.940
## 7     50 Masc Estrada       6             0.9793 0.8174 1.173
## 8     47 Masc Estrada       4             1.1783 0.9815 1.415
## 9     44 Masc Estrada      13             1.3499 1.1934 1.527
## 10    41 Masc Estrada      13             1.6099 1.4419 1.797</code></pre>
<p>Base de dados acompanhada das estimativas para a frequência média de sinistros e IC(95%).</p>
</div>
<div id="análise-de-deviance" class="section level2">
<h2>Análise de deviance</h2>
<p>Modelo nulo - modelo só com intercepto (um único parâmetro, comum a todas as observações)</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb117-1" data-line-number="1">ajusteNull &lt;-<span class="st"> </span><span class="kw">glm</span>(claims <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">family =</span> <span class="kw">poisson</span>(<span class="dt">link =</span> <span class="st">&#39;log&#39;</span>), <span class="dt">data =</span> dados)</a>
<a class="sourceLine" id="cb117-2" data-line-number="2"><span class="kw">summary</span>(ajusteNull)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = claims ~ 1, family = poisson(link = &quot;log&quot;), data = dados)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.843  -0.581  -0.581   0.225   3.926  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   0.5295     0.0343    15.4   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 733.84  on 499  degrees of freedom
## Residual deviance: 733.84  on 499  degrees of freedom
## AIC: 1723
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb119-1" data-line-number="1"><span class="kw">logLik</span>(ajusteNull) <span class="co"># log verossimilhança maximizada</span></a></code></pre></div>
<pre><code>## &#39;log Lik.&#39; -860.4 (df=1)</code></pre>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb121-1" data-line-number="1"><span class="kw">deviance</span>(ajusteNull) <span class="co"># deviance</span></a></code></pre></div>
<pre><code>## [1] 733.8</code></pre>
<p>Modelo saturado - modelo com n parâmetros (um para cada observação)</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb123-1" data-line-number="1">obs &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(dados))</a>
<a class="sourceLine" id="cb123-2" data-line-number="2">ajusteSat &lt;-<span class="st"> </span><span class="kw">glm</span>(claims <span class="op">~</span><span class="st"> </span>obs, <span class="dt">family=</span><span class="kw">poisson</span>(<span class="dt">link=</span><span class="st">&#39;log&#39;</span>),<span class="dt">data=</span>dados)</a>
<a class="sourceLine" id="cb123-3" data-line-number="3"><span class="kw">logLik</span>(ajusteSat) <span class="co"># log verossimilhança maximizada.</span></a></code></pre></div>
<pre><code>## &#39;log Lik.&#39; -493.5 (df=500)</code></pre>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb125-1" data-line-number="1"><span class="kw">deviance</span>(ajusteSat) <span class="co"># deviance.</span></a></code></pre></div>
<pre><code>## [1] 3.166e-10</code></pre>
<p>Para o modelo ajustado com as quatro covariáveis:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" data-line-number="1"><span class="kw">logLik</span>(ajuste2) </a></code></pre></div>
<pre><code>## &#39;log Lik.&#39; -784.3 (df=5)</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb129-1" data-line-number="1"><span class="kw">deviance</span>(ajuste2)</a></code></pre></div>
<pre><code>## [1] 581.5</code></pre>
<p>Análise de deviance</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb131-1" data-line-number="1"><span class="kw">anova</span>(ajuste2, <span class="dt">test=</span><span class="st">&#39;Chisq&#39;</span>)</a></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: poisson, link: log
## 
## Response: claims
## 
## Terms added sequentially (first to last)
## 
## 
##         Df Deviance Resid. Df Resid. Dev Pr(&gt;Chi)    
## NULL                      499        734             
## idade    1    139.2       498        595  &lt; 2e-16 ***
## sexo     1      1.5       497        593  0.21372    
## usop     1     11.4       496        582  0.00075 ***
## anosest  1      0.2       495        582  0.63276    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Repare na sequência de testes que são realizados: 1- Inclusão de idade ao modelo nulo (altamente significativa); 2- Inclusão de sexo ao modelo com idade (não significativa); 3- Inclusão de uso principal ao modelo com idade e sexo (altamente significativa); 4- Inclusão de anos de estudo ao modelo com as demais variáveis (não significativa).</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb133-1" data-line-number="1"><span class="kw">Anova</span>(ajuste2, <span class="dt">test =</span> <span class="st">&#39;LR&#39;</span>)</a></code></pre></div>
<pre><code>## Analysis of Deviance Table (Type II tests)
## 
## Response: claims
##         LR Chisq Df Pr(&gt;Chisq)    
## idade      135.8  1    &lt; 2e-16 ***
## sexo         0.0  1    0.83326    
## usop        11.5  1    0.00069 ***
## anosest      0.2  1    0.63276    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Repare na sequência de testes que são realizados: 1- Inclusão de idade ao modelo com as demais três variáveis (altamente significativa); 2- Inclusão de sexo ao modelo com as demais três variáveis (não significativa); 3- Inclusão de uso principal ao modelo com as demais três variáveis (altamente significativa); 4- Inclusão de anos de estudo ao modelo com as demais três variáveis (não significativa).</p>
<p>Experimente entrar na função glm com as variáveis em outra ordem e usar anova e Anova. Observe o que muda.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb135-1" data-line-number="1"><span class="kw">drop1</span>(ajuste2,<span class="dt">test =</span> <span class="st">&#39;Chisq&#39;</span>) </a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## claims ~ idade + sexo + usop + anosest
##         Df Deviance  AIC   LRT Pr(&gt;Chi)    
## &lt;none&gt;          582 1579                   
## idade    1      717 1712 135.8  &lt; 2e-16 ***
## sexo     1      582 1577   0.0  0.83326    
## usop     1      593 1588  11.5  0.00069 ***
## anosest  1      582 1577   0.2  0.63276    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Elimina uma variável por vez do modelo e testa a exclusão da variável via TRV. (similar a Anova) Não se verifica alteração significativa no ajuste resultante da exclusão do sexo, nem da exclusão dos anos de estudo. Para as outras duas, há fortes evidências que idade e uso principal estejam relacionadas ao número de sinistros.</p>
<p>Vamos explorar um pouco mais a parte de testes de hipóteses. Novamente, vamos testar o efeito de escolaridade e sexo, conjuntamente.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb137-1" data-line-number="1">ajuste2_rest &lt;-<span class="st"> </span><span class="kw">update</span>(ajuste2, <span class="op">~</span>.<span class="op">-</span>sexo<span class="op">-</span>anosest)</a></code></pre></div>
<p>Modelo sob a restrição.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" data-line-number="1"><span class="kw">anova</span>(ajuste2_rest, ajuste2, <span class="dt">test =</span> <span class="st">&#39;Chisq&#39;</span>)</a></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: claims ~ idade + usop
## Model 2: claims ~ idade + sexo + usop + anosest
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
## 1       497        582                     
## 2       495        582  2    0.281     0.87</code></pre>
<p>Não há efeito significativo de escolaridade e sexo. Podemos removê-las do modelo ajustado. Adicionalmente, vamos avaliar se há efeito de interação entre as variáveis remanescentes (uso principal e idade).</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" data-line-number="1">ajuste2 &lt;-<span class="st"> </span><span class="kw">update</span>(ajuste2_rest, <span class="op">~</span>.<span class="op">+</span>idade<span class="op">:</span>usop)</a>
<a class="sourceLine" id="cb140-2" data-line-number="2"><span class="kw">anova</span>(ajuste2_rest, ajuste2, <span class="dt">test =</span> <span class="st">&#39;Chisq&#39;</span>)</a></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: claims ~ idade + usop
## Model 2: claims ~ idade + usop + idade:usop
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)    
## 1       497        582                         
## 2       496        564  1     17.7  2.6e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>O efeito de interação é significativo. Fica como exercício explorar esse ajuste (escrever a expressão do modelo ajustado, apresentar algumas inferências e interpretações, fazer predições). Apenas adiantando, segue o resumo do ajuste.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" data-line-number="1"><span class="kw">summary</span>(ajuste2)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = claims ~ idade + usop + idade:usop, family = poisson(link = &quot;log&quot;), 
##     data = dados)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -2.730  -1.014  -0.144   0.559   2.788  
## 
## Coefficients:
##                   Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)        1.62408    0.31340    5.18  2.2e-07 ***
## idade             -0.03164    0.00803   -3.94  8.1e-05 ***
## usopEstrada        1.85696    0.38770    4.79  1.7e-06 ***
## idade:usopEstrada -0.04303    0.01014   -4.24  2.2e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 733.84  on 499  degrees of freedom
## Residual deviance: 564.13  on 496  degrees of freedom
## AIC: 1559
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div id="análise-de-deviance---avaliação-da-qualidade-do-ajuste." class="section level2">
<h2>Análise de deviance - avaliação da qualidade do ajuste.</h2>
<p>Vamos usar este modelo para avaliar a qualidade do ajuste com base na deviance residual. Vamos usar, a princípio, a aproximação com a distribuição qui-quadrado com n-p (496) graus de liberdade.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" data-line-number="1">ajuste2<span class="op">$</span>deviance </a></code></pre></div>
<pre><code>## [1] 564.1</code></pre>
<p>Deviance residual (estatística do teste da qualidade do ajuste).</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" data-line-number="1"><span class="kw">qchisq</span>(<span class="fl">0.05</span>, <span class="dt">df =</span> ajuste2<span class="op">$</span>df.residual, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## [1] 548.9</code></pre>
<p>Valor crítico.</p>
<p>Como a deviance excede o valor crítico, rejeitaríamos ao nível de significância de 5%, a hipótese nula de que o modelo ajustado está corretamente especificado. Vamos ver o valor-p do teste:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" data-line-number="1"><span class="kw">pchisq</span>(ajuste2<span class="op">$</span>deviance, <span class="dt">df =</span> ajuste2<span class="op">$</span>df.residual, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## [1] 0.01821</code></pre>
<p>p = 0.018, reforçando a evidência de que o modelo não é adequado. No entanto, é bem conhecido que a aproximação da deviance pela distribuição qui-quadrado (n-p), sob a hipótese nula de que o modelo é correto, nem sempre é apropriada. Então, como alternativa, vamos obter a distribuição sob H0 via simulação.</p>
<p>Para isso, precisamos simular dados sob a hipótese nula, de que o modelo é correto. Como fazemos isso?</p>
<p>Considere a primeira linha da base:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" data-line-number="1">dados[<span class="dv">1</span>,]</a></code></pre></div>
<pre><code>##   idade sexo    usop anosest claims
## 1    41  Fem Estrada      10      3</code></pre>
<p>Para esse indivíduo, o valor ajustado pelo modelo é dado por:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" data-line-number="1"><span class="kw">fitted</span>(ajuste2)[<span class="dv">1</span>]</a></code></pre></div>
<pre><code>##     1 
## 1.522</code></pre>
<p>Podemos simular uma resposta para essa observação, a partir do modelo, da seguinte forma:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" data-line-number="1"><span class="kw">rpois</span>(<span class="dv">1</span>, <span class="kw">fitted</span>(ajuste2)[<span class="dv">1</span>])</a></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>pronto. este valor foi simulado do modelo. Da mesma forma podemos simular uma observação para cada linha da base:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" data-line-number="1">dados<span class="op">$</span>y &lt;-<span class="st"> </span><span class="kw">rpois</span>(<span class="dv">500</span>, <span class="kw">fitted</span>(ajuste2))</a>
<a class="sourceLine" id="cb156-2" data-line-number="2">dados<span class="op">$</span>y</a></code></pre></div>
<pre><code>##   [1]  3  4  2  1  0  4  1  0  0  0  4  3  1  2  4  2  5  3  2  3  6  2  1
##  [24]  3  0  1  2  1  0  2  1  0  0  3  1  2  0  1  2  1  4  3  3  1  0  2
##  [47]  1  1  2  2  1  2  1  2  4  1  4  3  1  2  0  2  0  1  4  2  0  2  0
##  [70]  2  3  1  2  1  0  2  1  2  1  0  0  1  0  1  2  1  0  1  0  0  3  4
##  [93]  0  2  2  2  1  1  2  2  2  2  2  0  3  4  1  0  0  2  4  1  3  1  2
## [116]  0  2  1  0  0  1  2  1  1  1  1  1  2  0  0  1  4  1  1  1  3  0  1
## [139]  3  2  0  1  2  0  1  2  4  2  1  1  1  6  2  1  1  0  3  1  0  1  1
## [162]  1  0  2  2  1  0  2  3  1  2  1  1  2  0  2  1  1  1  0  0  6  2  3
## [185]  2  1  0  2  0  4  3  1  0  1  1  2  1  2  1  1  3  0  5  0  9  1  0
## [208]  0  2  1  2  2  0  2  1  2  2  0  0  1  0  2  1  3  2  1  2  1  5  0
## [231]  1  0  0  1  2  1  2  1  2  0  3  2  1  3  2  0  0  4  0  3  2  3  2
## [254]  2  4  1  2  4  0  0  4  1  2  1  1  5  2  0  0  0  2  4  2  1  2  1
## [277]  3  3  1  3  0  2  4  1  2  0  1  3  1  2  2  0  5  2 11  4  0  3  4
## [300]  1  0  1  8  1  0  2  0  2 11  0  1  1  3  2  3  1  2  2  1  2  5  2
## [323]  1  1  2  1  1  6  1  0  1  2  0  2  2  2  0  2  4  4  2  0  2  3  2
## [346]  4  1  1  1  2  4  3  1  1  5  0  3  2  1  2  4  1  2  1  0  0  2  1
## [369]  0  2  1  1  0  0  2  0  4  1  0  1  0  0  2  4  1  0  2  2  1  1  4
## [392]  1  0  2  1  3  2  0  3  0  2  1  1  1  4  2  4  1  0  1  3  5  1  3
## [415]  0  3  0  1  4  1  5  2  2  2  0  1  1  2  2  3  1  1  1  1  7  1  1
## [438]  3  2  1  5  1  1  3  1  0  2  1  1  1  3  2  0  3  2  2  0  0  3  3
## [461]  3  1  2  3  0  2  1  0  2  4  4  1  3  2  3  1  2  5  5  2  0  2  0
## [484]  1  0  5  1  6  0  1  1  1  4  1  5  3  2  1  1  3</code></pre>
<p>Agora, usamos esse vetor de respostas em substituição ao vetor original no ajuste do modelo.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" data-line-number="1">ajuste2Sim &lt;-<span class="st"> </span><span class="kw">glm</span>(y<span class="op">~</span><span class="st"> </span>idade <span class="op">+</span><span class="st"> </span>anosest <span class="op">+</span><span class="st"> </span>usop <span class="op">+</span><span class="st"> </span>sexo, <span class="dt">family =</span> poisson, <span class="dt">data =</span> dados)</a>
<a class="sourceLine" id="cb158-2" data-line-number="2"><span class="kw">deviance</span>(ajuste2Sim)</a></code></pre></div>
<pre><code>## [1] 566.3</code></pre>
<p>Esta é uma deviance simulada sob H0. Para construir a distribuição empírica sob H0, temos que repetir a simulação um grande número de vezes (digamos 1000).</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" data-line-number="1">vet_deviance &lt;-<span class="st"> </span><span class="kw">numeric</span>() <span class="co"># Vetor que vai armazenar as deviances</span></a></code></pre></div>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" data-line-number="1"><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>){</a>
<a class="sourceLine" id="cb161-2" data-line-number="2">  dados<span class="op">$</span>y &lt;-<span class="st"> </span><span class="kw">rpois</span>(<span class="dv">500</span>, <span class="kw">fitted</span>(ajuste2))</a>
<a class="sourceLine" id="cb161-3" data-line-number="3">  ajuste2Sim &lt;-<span class="st"> </span><span class="kw">glm</span>(y<span class="op">~</span><span class="st"> </span>idade <span class="op">+</span><span class="st"> </span>anosest <span class="op">+</span><span class="st"> </span>usop <span class="op">+</span><span class="st"> </span>sexo, <span class="dt">family =</span> poisson, <span class="dt">data =</span> dados)</a>
<a class="sourceLine" id="cb161-4" data-line-number="4">  vet_deviance[i] &lt;-<span class="st"> </span><span class="kw">deviance</span>(ajuste2Sim)</a>
<a class="sourceLine" id="cb161-5" data-line-number="5">}</a>
<a class="sourceLine" id="cb161-6" data-line-number="6"></a>
<a class="sourceLine" id="cb161-7" data-line-number="7"><span class="kw">hist</span>(vet_deviance)</a>
<a class="sourceLine" id="cb161-8" data-line-number="8"><span class="kw">abline</span>(<span class="dt">v =</span> ajuste2<span class="op">$</span>deviance, <span class="dt">col =</span> <span class="st">&#39;red&#39;</span>)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<p>Fica bem evidente que o valor calculado da deviance não é atípico ou extremo em relação aos valores simulados sob H0, o que é um indicativo de que o modelo se ajusta bem aos dados. Vamos calcular o p-valor com base na distribuição empírica, pela proporção de valores simulados que excedem o valor original da deviance.</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb162-1" data-line-number="1"><span class="kw">mean</span>(vet_deviance <span class="op">&gt;</span><span class="st"> </span><span class="kw">deviance</span>(ajuste2))</a></code></pre></div>
<pre><code>## [1] 0.723</code></pre>
<p>Ou seja, não temos evidência de falta de ajuste do modelo.</p>
</div>
<div id="diagnóstico-do-ajuste" class="section level2">
<h2>Diagnóstico do ajuste</h2>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb164-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">cex =</span> <span class="fl">1.25</span>, <span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb164-2" data-line-number="2"><span class="kw">plot</span>(ajuste2)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p>Os resíduos utlizados ao plotar um objeto da classe glm são os resíduos componentes da deviance. Nem sempre esses resíduos têm boa aproximação com a distribuição normal se o modelo ajustado estiver correto. Isso ocorre, particularmente, para dados binários ou de contagens. Esse fato será verificado através de um novo estudo por simulação, apresentado ao final dos scripts. Voltando à análise dos dados, é possível notar comportamento mais aceitável (variância mais homogênea, melhor aproximação com a distribuição Normal) em relação ao que foi verificado para o modelo linear.</p>
<p>para uma melhor apreciação do comportamento dos resíduos, vamos proceder com a análise dos resíduos quantílicos aleatorizados e a obtenção do gráfico meio normal com envelopes simulados.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" data-line-number="1"><span class="kw">require</span>(statmod)</a>
<a class="sourceLine" id="cb165-2" data-line-number="2">residuos &lt;-<span class="st"> </span><span class="kw">qres.pois</span>(ajuste2)</a>
<a class="sourceLine" id="cb165-3" data-line-number="3">ajustados &lt;-<span class="st"> </span><span class="kw">predict</span>(ajuste2)</a>
<a class="sourceLine" id="cb165-4" data-line-number="4"></a>
<a class="sourceLine" id="cb165-5" data-line-number="5"></a>
<a class="sourceLine" id="cb165-6" data-line-number="6"><span class="kw">par</span>(<span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="dt">cex =</span> <span class="fl">1.4</span>)</a>
<a class="sourceLine" id="cb165-7" data-line-number="7"><span class="kw">plot</span>(residuos <span class="op">~</span><span class="st"> </span>ajustados, <span class="dt">col =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">xlab =</span> <span class="st">&#39;Valores ajustados&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Resíduos&#39;</span>)</a>
<a class="sourceLine" id="cb165-8" data-line-number="8"><span class="kw">lines</span>(<span class="kw">lowess</span>(residuos <span class="op">~</span><span class="st"> </span>ajustados), <span class="dt">col =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb165-9" data-line-number="9"><span class="kw">qqnorm</span>(residuos, <span class="dt">col =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">main =</span> <span class="st">&#39;&#39;</span>)</a>
<a class="sourceLine" id="cb165-10" data-line-number="10"><span class="kw">qqline</span>(residuos, <span class="dt">lty =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-75-1.png" width="672" /></p>
<p>A curvatura da função suave, presente no gráfico à esquerda, é resultante da pequena quantidade de pontos nos extremos dos valores ajustados. De qualquer forma, fica evidente que os resíduos tem dispersão aproxim. constante e boa aproximação com a distribuição Normal.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb166-1" data-line-number="1"><span class="kw">shapiro.test</span>(residuos) <span class="co"># teste de Shapiro-Wilks para normalidade.</span></a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuos
## W = 1, p-value = 0.5</code></pre>
<p>A hipótese nula de normalidade não é rejeitada.</p>
<p>Como alternativa, vamos usar os gráficos meio normais com envelopes simulados.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb168-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">5</span>,<span class="fl">4.5</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">cex =</span> <span class="fl">1.4</span>)</a>
<a class="sourceLine" id="cb168-2" data-line-number="2"><span class="kw">hnp</span>(ajuste2)</a></code></pre></div>
<pre><code>## Poisson model</code></pre>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-77-1.png" width="672" /></p>
<p>O gráfico indica que o modelo se ajusta bem aos dados.</p>
<p>Gráficos de resíduos parciais Usando recursos de diagnóstico do pacote car:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb170-1" data-line-number="1"><span class="co"># crPlots(ajuste2, cex = 2, pch = 20) </span></a></code></pre></div>
<p>Gráficos de resíduos parciais</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb171-1" data-line-number="1"><span class="kw">residualPlots</span>(ajuste2, <span class="dt">cex =</span> <span class="dv">2</span>, <span class="dt">pch =</span> <span class="dv">20</span>) </a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-79-1.png" width="672" /></p>
<pre><code>##       Test stat Pr(&gt;|Test stat|)
## idade      0.28              0.6
## usop</code></pre>
<p>Gráfico de resíduos versus variáveis ajustadas no modelo.</p>
</div>
<div id="diagnóstico-de-outliers-e-pontos-influentes." class="section level2">
<h2>Diagnóstico de outliers e pontos influentes.</h2>
<p>Vamos fazer uma análise de influência usando recursos do pacote car.</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" data-line-number="1"><span class="kw">influenceIndexPlot</span>(ajuste2, <span class="dt">vars =</span> <span class="kw">c</span>(<span class="st">&#39;Studentized&#39;</span>,<span class="st">&#39;Cook&#39;</span>,<span class="st">&#39;Hat&#39;</span>), <span class="dt">id.n =</span> <span class="dv">3</span>)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-80-1.png" width="672" /></p>
<p>O gráfico dos resíduos studentizados não indica observações com resíduos extremos. O gráfico da distância de Cook tem dois pontos mais discrepantes: 15 e 385. O gráfico dos valores de h aponta a observação 295 como possível ponto de alavanca.</p>
<p>Vamos avaliar os dados destacados na análise.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb174-1" data-line-number="1">dados[<span class="dv">15</span>,]</a></code></pre></div>
<pre><code>##    idade sexo    usop anosest claims  y
## 15    29 Masc Estrada       6      9 11</code></pre>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb176-1" data-line-number="1">dados[<span class="dv">295</span>,]</a></code></pre></div>
<pre><code>##     idade sexo    usop anosest claims  y
## 295    16 Masc Estrada      16      9 14</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" data-line-number="1">dados[<span class="dv">385</span>,]</a></code></pre></div>
<pre><code>##     idade sexo   usop anosest claims y
## 385    47  Fem Cidade      14      5 1</code></pre>
<p>Vamos ver o summary dos dados e do ajuste para entender melhor o por que desse dados serem destacados.</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" data-line-number="1"><span class="kw">summary</span>(dados)</a></code></pre></div>
<pre><code>##      idade        sexo          usop        anosest         claims   
##  Min.   :16.0   Fem :191   Cidade :237   Min.   : 4.0   Min.   :0.0  
##  1st Qu.:35.0   Masc:309   Estrada:263   1st Qu.: 7.0   1st Qu.:1.0  
##  Median :40.0                            Median :10.0   Median :1.0  
##  Mean   :39.9                            Mean   :10.3   Mean   :1.7  
##  3rd Qu.:45.0                            3rd Qu.:13.0   3rd Qu.:2.0  
##  Max.   :61.0                            Max.   :17.0   Max.   :9.0  
##        y        
##  Min.   : 0.00  
##  1st Qu.: 1.00  
##  Median : 1.00  
##  Mean   : 1.79  
##  3rd Qu.: 2.00  
##  Max.   :14.00</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" data-line-number="1"><span class="kw">summary</span>(ajuste2)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = claims ~ idade + usop + idade:usop, family = poisson(link = &quot;log&quot;), 
##     data = dados)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -2.730  -1.014  -0.144   0.559   2.788  
## 
## Coefficients:
##                   Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)        1.62408    0.31340    5.18  2.2e-07 ***
## idade             -0.03164    0.00803   -3.94  8.1e-05 ***
## usopEstrada        1.85696    0.38770    4.79  1.7e-06 ***
## idade:usopEstrada -0.04303    0.01014   -4.24  2.2e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 733.84  on 499  degrees of freedom
## Residual deviance: 564.13  on 496  degrees of freedom
## AIC: 1559
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>O indivíduo 15 gerou nove sinistros, sendo o segurado com maior número de sinistros;</p>
<p>O indivíduo 385 tem 47 anos e usa o carro na cidade, mas registrou um número elevado de sinistros (cinco).</p>
<p>O indivíduo 295 é atípico, tem 16 anos de idade e 16 de estudo!!! Deve ser erro de registro.</p>
<p>Vamos tirar da base as observações 15, 295 e 385 e reajustar o modelo.</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb184-1" data-line-number="1">ajuste3 &lt;-<span class="st"> </span><span class="kw">update</span>(ajuste2, <span class="dt">subset=</span> <span class="op">-</span><span class="kw">c</span>(<span class="dv">15</span>,<span class="dv">295</span>,<span class="dv">385</span>))</a>
<a class="sourceLine" id="cb184-2" data-line-number="2"><span class="kw">compareCoefs</span>(ajuste2, ajuste3) </a></code></pre></div>
<pre><code>## Calls:
## 1: glm(formula = claims ~ idade + usop + idade:usop, family = 
##   poisson(link = &quot;log&quot;), data = dados)
## 2: glm(formula = claims ~ idade + usop + idade:usop, family = 
##   poisson(link = &quot;log&quot;), data = dados, subset = -c(15, 295, 385))
## 
##                    Model 1  Model 2
## (Intercept)          1.624    1.696
## SE                   0.313    0.316
##                                    
## idade             -0.03164 -0.03381
## SE                 0.00803  0.00812
##                                    
## usopEstrada          1.857    1.737
## SE                   0.388    0.405
##                                    
## idade:usopEstrada  -0.0430  -0.0398
## SE                  0.0101   0.0106
## </code></pre>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb186-1" data-line-number="1"><span class="kw">multiplot</span>(ajuste2, ajuste3) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">20</span>)</a></code></pre></div>
<p><img src="sini_auto_mod6_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>Comparação de estimativas e erros padrões produzidos pelos dois modelos. Os resultados (e, consequentemente, as inferências) não mudam de forma substancial ao remover as três informações da base.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4,h5",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
