<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Cesar Taconeli" />


<title>Vendas de cosméticos (Modelo com erros normais)</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Gian Lima</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="https://gianlima.github.io/">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    GLM 1-9
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Conteúdo de GLM</li>
    <li class="dropdown-header">Módulo 2 - Revisão de modelos lineares</li>
    <li>
      <a href="reacao_mod2.html">Reação química + tipos de embalagens (Modelo com erros normais)</a>
    </li>
    <li>
      <a href="venda_cos_mod2.html">Vendas de cosméticos (Modelo com erros normais)</a>
    </li>
    <li>
      <a href="min_qua_pon_mod3.html">Módulo 3 - Modelo linear com erros heterocedásticos</a>
    </li>
    <li class="dropdown-header">Módulo 6 - Estimação em modelos lineares generalizados</li>
    <li>
      <a href="estim_glm_mod6.html">Estimação em modelos lineares generalizados</a>
    </li>
    <li>
      <a href="sini_auto_mod6.html">Sinistros de Automóveis (Dados de contagens)</a>
    </li>
    <li>
      <a href="aval_qua_mod8.html">Módulo 8 - Análise de deviance</a>
    </li>
    <li>
      <a href="sel_var_mod9.html">Módulo 9 - Seleção de covariáveis</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    GLM 10-15
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="diag_mod10.html">Módulo 10 - Diagnóstico do ajuste de MLGs</a>
    </li>
    <li class="dropdown-header">Módulo 11 - Regressão para dados binários</li>
    <li>
      <a href="besouro_mod11.html">Auditoria</a>
    </li>
    <li>
      <a href="besouro_mod11.html">Besouro da Farinha</a>
    </li>
    <li>
      <a href="estimacao_mod11.html">Estimação em MLG usando bootstrap</a>
    </li>
    <li>
      <a href="plebis_mod11.html">Plebiscito no Chile</a>
    </li>
    <li class="dropdown-header">Módulo 12 - Regressão para dados binários - predição</li>
    <li>
      <a href="credito_mod12.html">Análise de risco de crédito</a>
    </li>
    <li>
      <a href="base_mod12.html">Base de dados sobre spams</a>
    </li>
    <li class="dropdown-header">Módulo 13 - Regressão para dados de contagens</li>
    <li>
      <a href="queda_idoso_mod13.html">Quedas de idosos</a>
    </li>
    <li>
      <a href="cromo_mod13.html">Cromossomos anormais (Regressão Poisson com termo offset)</a>
    </li>
    <li class="dropdown-header">Módulo 14 - Regressão para dados de contagens com super dispersão</li>
    <li>
      <a href="super_disp_mod14.html">superdispersão (simulação)</a>
    </li>
    <li>
      <a href="exe_comp_mod14.html">Executivos compartilhados</a>
    </li>
    <li>
      <a href="Consulta_mod14.html">Número de consultas ao médico (Austrália)</a>
    </li>
    <li>
      <a href="ratos_mod14.html">Suplementação de ferro em ratos</a>
    </li>
    <li>
      <a href="cevada_mod14.html">Doença da cevada</a>
    </li>
    <li class="dropdown-header">Módulo 15 - Regressão para dados contínuos assimétricos</li>
    <li>
      <a href="turbina_mod15.html">Tempo de vida de turbinas de avião</a>
    </li>
    <li>
      <a href="tweedie_valor_sin_mod15.html">Valor de sinistros</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/gianlima/r-exams-tutorial">
    <span class="fa fa-github fa-lg"></span>
     
    GitHub
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Vendas de cosméticos (Modelo com erros normais)</h1>
<h4 class="author">Cesar Taconeli</h4>

</div>


<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">require</span>(effects)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">require</span>(car)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw">require</span>(leaps) </a></code></pre></div>
<p>Exemplo - Regressão Linear Múltipla para os dados de vendas de cosméticos. O objetivo é propor e ajustar um modelo de regressão para explicar o total em vendas em função do tempo de serviço, idade, anos de estudo e Populacao atendida pelas vendedoras.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">vendas &lt;-<span class="st"> </span><span class="kw">read.csv2</span>(<span class="st">&quot;Normal2.csv&quot;</span>)</a>
<a class="sourceLine" id="cb2-2" data-line-number="2"></a>
<a class="sourceLine" id="cb2-3" data-line-number="3"><span class="kw">names</span>(vendas) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;Tempo&#39;</span>, <span class="st">&#39;Idade&#39;</span>, <span class="st">&#39;Estudo&#39;</span>, <span class="st">&#39;Populacao&#39;</span>, <span class="st">&#39;Venda&#39;</span>)</a>
<a class="sourceLine" id="cb2-4" data-line-number="4"></a>
<a class="sourceLine" id="cb2-5" data-line-number="5"><span class="kw">summary</span>(vendas) <span class="co"># Resumo numérico dos valores das cinco variáveis disponíveis na amostra.</span></a></code></pre></div>
<pre><code>##      Tempo           Idade          Estudo        Populacao    
##  Min.   : 0.00   Min.   :23.0   Min.   : 4.00   Min.   :  128  
##  1st Qu.: 7.00   1st Qu.:35.0   1st Qu.: 6.00   1st Qu.: 7595  
##  Median :10.00   Median :40.0   Median : 8.00   Median :10399  
##  Mean   : 9.85   Mean   :39.6   Mean   : 8.65   Mean   :10143  
##  3rd Qu.:13.00   3rd Qu.:44.0   3rd Qu.:11.00   3rd Qu.:12618  
##  Max.   :20.00   Max.   :57.0   Max.   :17.00   Max.   :21203  
##      Venda      
##  Min.   : 4008  
##  1st Qu.:10508  
##  Median :12708  
##  Mean   :12597  
##  3rd Qu.:14584  
##  Max.   :20775</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="kw">options</span>(<span class="dt">digits =</span> <span class="dv">5</span>, <span class="dt">scipen =</span> <span class="dv">5</span>)</a>
<a class="sourceLine" id="cb4-2" data-line-number="2"></a>
<a class="sourceLine" id="cb4-3" data-line-number="3"><span class="kw">require</span>(car)</a>
<a class="sourceLine" id="cb4-4" data-line-number="4"><span class="kw">par</span>(<span class="dt">cex=</span><span class="fl">1.2</span>)</a>
<a class="sourceLine" id="cb4-5" data-line-number="5"><span class="kw">scatterplotMatrix</span>(vendas, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">cex.labels =</span> <span class="fl">1.25</span>) </a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Matriz de gráficos de dispersão (com gráficos das densidades estimadas na diagonal). Os gráficos de dispersão fornecem um primeiro indicativo de tendência crescente entre Populacao atendida e total de vendas e, com menor intensidade, entre total de vendas e tempo de serviço.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">ajuste1 &lt;-<span class="st"> </span><span class="kw">lm</span>(Venda <span class="op">~</span><span class="st"> </span>Tempo<span class="op">+</span>Estudo<span class="op">+</span>Populacao<span class="op">+</span>Idade, <span class="dt">data=</span>vendas) </a></code></pre></div>
<p>Ajuste da regressão linear múltipla, considerando as quatro covariáveis. Nota: uma forma equivalente de ajustar o modelo acima seria</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1">ajuste1=<span class="kw">lm</span>(Venda<span class="op">~</span>.,<span class="dt">data=</span>vendas)</a>
<a class="sourceLine" id="cb6-2" data-line-number="2"></a>
<a class="sourceLine" id="cb6-3" data-line-number="3"><span class="kw">print</span>(ajuste1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Venda ~ ., data = vendas)
## 
## Coefficients:
## (Intercept)        Tempo        Idade       Estudo    Populacao  
##    3204.051      174.378       18.012       67.800        0.629</code></pre>
<p>Extraindo as estimativas dos parâmetros da regressão.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="kw">summary</span>(ajuste1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Venda ~ ., data = vendas)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -4381  -1299     26   1309   5848 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 3204.0510   900.8786    3.56  0.00047 ***
## Tempo        174.3781    40.9153    4.26 0.000032 ***
## Idade         18.0119    22.3506    0.81  0.42129    
## Estudo        67.8001    48.0258    1.41  0.15962    
## Populacao      0.6286     0.0373   16.86  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1910 on 195 degrees of freedom
## Multiple R-squared:  0.634,  Adjusted R-squared:  0.626 
## F-statistic: 84.3 on 4 and 195 DF,  p-value: &lt;2e-16</code></pre>
<p>Os resultados do ajuste indicam que o total em vendas aumenta conforme o tempo de experiência e a Populacao atendida. Para as demais variáveis, não há evidência significativa de que estejam relacionadas ao total em vendas. Estima-se que o total em vendas aumente, em média, R$174,37 para um ano a mais de experiência, mantendo-se fixas as demais covariáveis. Quanto à Populacao atendida, estima-se, em média, R$0,628 a mais por pessoa. Assim, para 1000 pessoas a mais na Populacao, estima-se, em média, R$628 a mais no total de vendas, mantendo-se fixas as demais covariáveis.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">ajuste1sc &lt;-<span class="st"> </span><span class="kw">lm</span>(Venda <span class="op">~</span><span class="st"> </span><span class="kw">scale</span>(Tempo)<span class="op">+</span><span class="kw">scale</span>(Idade)<span class="op">+</span><span class="kw">scale</span>(Estudo)<span class="op">+</span><span class="kw">scale</span>(Populacao), <span class="dt">data=</span>vendas)</a>
<a class="sourceLine" id="cb10-2" data-line-number="2"><span class="kw">summary</span>(ajuste1sc)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Venda ~ scale(Tempo) + scale(Idade) + scale(Estudo) + 
##     scale(Populacao), data = vendas)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -4381  -1299     26   1309   5848 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         12597        135   93.38  &lt; 2e-16 ***
## scale(Tempo)          708        166    4.26 0.000032 ***
## scale(Idade)          125        155    0.81     0.42    
## scale(Estudo)         214        152    1.41     0.16    
## scale(Populacao)     2296        136   16.86  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1910 on 195 degrees of freedom
## Multiple R-squared:  0.634,  Adjusted R-squared:  0.626 
## F-statistic: 84.3 on 4 and 195 DF,  p-value: &lt;2e-16</code></pre>
<p>Neste novo modelo, todas as variáveis explicativas foram padronizadas (subtraímos, de cada valor, a média da variável e dividimos pelo respectivo desvio padrão). Assim, as variáveis agora têm mesma escala e seus efeitos são diretamente comparáveis.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw">head</span>(<span class="kw">fitted</span>(ajuste1), <span class="dt">n =</span> <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##       1       2       3       4       5       6       7       8       9 
## 11734.0 11382.9  9709.5  8605.9 18879.6  5997.7 11349.9  9315.6 15271.2 
##      10 
## 14719.2</code></pre>
<p>Valores ajustados pelo modelo de regressão linear múltipla para as 200 vendedoras.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="kw">plot</span>(<span class="kw">fitted</span>(ajuste1), vendas<span class="op">$</span>Venda,<span class="dt">pch=</span><span class="dv">20</span>, <span class="dt">xlab=</span><span class="st">&#39;Vendas ajustadas&#39;</span>, <span class="dt">ylab=</span><span class="st">&#39;Vendas observadas&#39;</span>,<span class="dt">las=</span><span class="dv">1</span>,<span class="dt">cex =</span> <span class="fl">1.2</span>) </a>
<a class="sourceLine" id="cb14-2" data-line-number="2"><span class="kw">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dt">col=</span><span class="st">&#39;red&#39;</span>,<span class="dt">lwd =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Gráfico de valores observados pelos valores ajustados.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="kw">confint</span>(ajuste1) </a></code></pre></div>
<pre><code>##                  2.5 %    97.5 %
## (Intercept) 1427.33465 4980.7673
## Tempo         93.68469  255.0715
## Idade        -26.06801   62.0919
## Estudo       -26.91661  162.5169
## Populacao      0.55507    0.7021</code></pre>
<p>Intervalos de confiança (95%) para os parâmetros do modelo.</p>
<p>Agora, algumas predições.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">dnovos &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Tempo=</span><span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">15</span>), <span class="dt">Idade=</span><span class="kw">c</span>(<span class="dv">30</span>,<span class="dv">30</span>), <span class="dt">Estudo=</span><span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">10</span>), <span class="dt">Populacao=</span><span class="kw">c</span>(<span class="dv">1000</span>,<span class="dv">10000</span>)) </a>
<a class="sourceLine" id="cb17-2" data-line-number="2">dnovos</a></code></pre></div>
<pre><code>##   Tempo Idade Estudo Populacao
## 1     3    30     10      1000
## 2    15    30     10     10000</code></pre>
<p>Dois perfis de vendedoras para estimarmos o total médio de vendas e predizer o total de vendas</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw">predict</span>(ajuste1, <span class="dt">newdata=</span>dnovos) <span class="co"># Estimativas pontuais.</span></a></code></pre></div>
<pre><code>##       1       2 
##  5574.1 13323.9</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw">predict</span>(ajuste1, <span class="dt">interval=</span><span class="st">&#39;confidence&#39;</span>, <span class="dt">newdata=</span>dnovos) </a></code></pre></div>
<pre><code>##       fit     lwr     upr
## 1  5574.1  4671.4  6476.8
## 2 13323.9 12579.5 14068.3</code></pre>
<p>Intervalos de confiança (95%) para o total médio de vendas.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw">predict</span>(ajuste1, <span class="dt">interval=</span><span class="st">&#39;prediction&#39;</span>, <span class="dt">newdata=</span>dnovos) </a></code></pre></div>
<pre><code>##       fit    lwr     upr
## 1  5574.1 1704.9  9443.4
## 2 13323.9 9488.5 17159.3</code></pre>
<p>Intervalos de predição (95%) para a predição do total de vendas.</p>
<p>Agora, vamos fazer estimativas e predições “no atacado”, usando todos os vetores de covariáveis (perfis de vendedoras) da base.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1">p1 &lt;-<span class="st"> </span><span class="kw">predict</span>(ajuste1, <span class="dt">interval=</span><span class="st">&#39;confidence&#39;</span>, <span class="dt">newdata=</span>vendas)</a>
<a class="sourceLine" id="cb25-2" data-line-number="2">vendas2 &lt;-<span class="st"> </span><span class="kw">cbind</span>(vendas[,<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>], p1); <span class="kw">head</span>(vendas2, <span class="dv">10</span>) </a></code></pre></div>
<pre><code>##    Tempo Idade Estudo Populacao     fit     lwr     upr
## 1      1    28      5     11951 11734.0 11048.9 12419.0
## 2      3    23      5     10981 11382.9 10666.1 12099.8
## 3      3    40      7      7616  9709.5  9102.2 10316.8
## 4      6    37      7      5114  8605.9  8090.5  9121.4
## 5     17    42     12     17724 18879.6 18096.1 19663.1
## 6     10    35      5       128  5997.7  5090.0  6905.5
## 7      6    45      6      9358 11349.9 10797.2 11902.7
## 8      7    32      8      6001  9315.6  8817.4  9813.8
## 9     14    41      9     13168 15271.2 14824.1 15718.3
## 10     8    42     11     13710 14719.2 14193.9 15244.6</code></pre>
<p>Em vendas2 armazenamos os dados e os correspondentes ICs (95%) para o total médio de vendas.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1">p2 &lt;-<span class="st"> </span><span class="kw">predict</span>(ajuste1, <span class="dt">interval =</span><span class="st">&#39;prediction&#39;</span>, <span class="dt">newdata=</span>vendas)</a>
<a class="sourceLine" id="cb27-2" data-line-number="2">vendas3 &lt;-<span class="st"> </span><span class="kw">cbind</span>(vendas[,<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>], p2) ;<span class="kw">head</span>(vendas3, <span class="dv">10</span>) </a></code></pre></div>
<pre><code>##    Tempo Idade Estudo Populacao     fit     lwr     upr
## 1      1    28      5     11951 11734.0  7909.6 15558.3
## 2      3    23      5     10981 11382.9  7552.8 15213.1
## 3      3    40      7      7616  9709.5  5898.4 13520.7
## 4      6    37      7      5114  8605.9  4808.3 12403.5
## 5     17    42     12     17724 18879.6 15036.4 22722.8
## 6     10    35      5       128  5997.7  2127.3  9868.1
## 7      6    45      6      9358 11349.9  7547.1 15152.8
## 8      7    32      8      6001  9315.6  5520.3 13110.9
## 9     14    41      9     13168 15271.2 11482.3 19060.2
## 10     8    42     11     13710 14719.2 10920.3 18518.2</code></pre>
<p>Em vendas3 armazenamos os dados e os correspondentes IPs (95%) para o total de vendas de novas vendedoras.</p>
<p>Vamos usar o teste F, baseado na extra soma de quadrados para testar algumas hipóteses. H0: Beta(idade)=0 vs H1: Beta(idade)!=0 (testando a significância do efeito da idade)</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1">ajuste2 &lt;-<span class="st"> </span><span class="kw">lm</span>(Venda<span class="op">~</span>.<span class="op">-</span>Idade,<span class="dt">data=</span>vendas) </a></code></pre></div>
<p>Modelo de regressão linear múltipla sem considerar a covariável idade.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1"><span class="kw">anova</span>(ajuste2,ajuste1) </a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Venda ~ (Tempo + Idade + Estudo + Populacao) - Idade
## Model 2: Venda ~ Tempo + Idade + Estudo + Populacao
##   Res.Df       RSS Df Sum of Sq    F Pr(&gt;F)
## 1    196 712067051                         
## 2    195 709703391  1   2363660 0.65   0.42</code></pre>
<p>Repare que o acréscimo na soma de quadrados (vamos chamar de ASQ) de regressão associado à inclusão do efeito de idade é de 2363660, ao qual temos um grau de liberdade associado.</p>
<p>A estatística do teste é F=(ASQ/1)/QMRes, onde QMRes é o quadrado médio de resíduos do modelo “maior”, que pode ser verificado batendo anova(ajuste1).</p>
<p>Sob H0, F~F(1,195) (faça o teste à mão, para um nível de significância de 5%).</p>
<p>Algumas considerações: 1 - O efeito de idade é não significativo, o que poderia justificar a exclusão dessa variável do modelo.</p>
<p>2 - O teste F é equivalente ao teste t apresentado no summary. Isso não é coincidência, e sempre ocorrerá quando houver apenas um parâmetro do modelo sob teste.</p>
<p>3 - Repare a saída da função anova() aplicada a um único modelo. Ela apresenta a seguinte sequência de testes:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1"><span class="kw">anova</span>(ajuste1)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Venda
##            Df     Sum Sq    Mean Sq F value  Pr(&gt;F)    
## Tempo       1  191606685  191606685   52.65 9.2e-12 ***
## Idade       1     866557     866557    0.24    0.63    
## Estudo      1     260371     260371    0.07    0.79    
## Populacao   1 1034980948 1034980948  284.37 &lt; 2e-16 ***
## Residuals 195  709703391    3639505                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>I- Linha 1 - Testa a inclusão do efeito de Tempo ao modelo nulo (sem covariáveis) - significativa.</p>
<p>II- Linha 2 - Testa a inclusão do efeito de Idade ao modelo com a covariável tempo - não significativa.</p>
<p>III- Linha 3 - Testa a inclusão do efeito de Anos de estudo ao modelo com as covariáveis tempo e idade - não significativa.</p>
<p>IV- Linha 4 - Testa a inclusão do efeito de Populacao ao modelo com as covariáveis tempo, idade e anos de estudo - significativa.</p>
<p>Nota - Em todos os testes, usa-se QMRes produzida pelo modelo ajustado com mais parâmetros (no caso, o modelo com as quatro covariáveis). Repare que os testes não são equivalentes aos do summary (exceto o último). Por que?</p>
<p>Pergunta - o que aconteceria com a sequência de testes se você mudasse a ordem de entrada das variáveis na função lm?</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1">ajuste2 &lt;-<span class="st"> </span><span class="kw">lm</span>(Venda<span class="op">~</span>Populacao<span class="op">+</span>Estudo<span class="op">+</span>Idade<span class="op">+</span>Tempo, <span class="dt">data=</span>vendas) </a></code></pre></div>
<p>Ajuste da regressão linear múltipla, considerando as quatro covariáveis, com elas inseridas em ordem invertida.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1"><span class="kw">anova</span>(ajuste2)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Venda
##            Df     Sum Sq    Mean Sq F value   Pr(&gt;F)    
## Populacao   1 1069238001 1069238001  293.79  &lt; 2e-16 ***
## Estudo      1   63098117   63098117   17.34 0.000047 ***
## Idade       1   29270468   29270468    8.04   0.0051 ** 
## Tempo       1   66107975   66107975   18.16 0.000032 ***
## Residuals 195  709703391    3639505                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Agora, vamos dar uma olhada no resultado da função Anova (com A maiúsculo), disponível no pacote car.</p>
<p>Anova(ajuste1) A sequência de testes agora é a seguinte: I- Linha 1 - Testa a inclusão do efeito de Tempo ao modelo ajustado com as outras três covariáveis - significativa.</p>
<p>II- Linha 2 - Testa a inclusão do efeito de Idade ao modelo ajustado com as outras três covariáveis - não significativa.</p>
<p>III- Linha 3 - Testa a inclusão do efeito de Anos de estudo ao modelo ajustado com as outras três covariáveis - não significativa.</p>
<p>IV- Linha 4 - Testa a inclusão do efeito de Populacao ao modelo ajustado com as outras três covariáveis - significativa.</p>
<p>Repare que os testes fornecidos por essa função são equivalentes aos do summary. Por que?</p>
<p>Anova(ajuste2) Com as variáveis inseridas em ordem diferente… Mesmo resultado.</p>
<p>Agora, vamos usar o teste F para testar a hipótese de nulidade conjunta H0:Beta(Idade)=Beta(Estudo)=0. Esse teste permite verificar a contribuição ##conjunta das duas variáveis ao modelo.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1">ajuste3 &lt;-<span class="st"> </span><span class="kw">lm</span>(Venda <span class="op">~</span><span class="st"> </span>Populacao<span class="op">+</span>Tempo,<span class="dt">data=</span>vendas) </a></code></pre></div>
<p>ajuste3 armazena o modelo ajustado sob H0, ou seja, não incluindo as covariáveis para as quais estamos postulando que o correspondente parâmetro é nulo.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1"><span class="kw">anova</span>(ajuste3,ajuste1) </a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Venda ~ Populacao + Tempo
## Model 2: Venda ~ Tempo + Idade + Estudo + Populacao
##   Res.Df       RSS Df Sum of Sq    F Pr(&gt;F)
## 1    197 720103307                         
## 2    195 709703391  2  10399916 1.43   0.24</code></pre>
<p>Repare que a extra-soma de quadrados (10399916, com 2 graus de liberdade) não é significativa (p=0,2421), o que pode justificar a exclusão das duas covariáveis (Estudo e Idade) do modelo.</p>
<p>O teste é obtido por (ASQ/2)/QMRes, sendo QMRes=3639505 extraída do modelo ajustado com mais parâmetros.</p>
<p>Nota: Ao observar que duas covariáveis não são marginalmente significativas no ajuste de um modelo, isso não implica que elas sejam não significativas conjuntamente. A não significância conjunta deve ser testada com base no teste F da extra-soma de quadrados.</p>
<p>Agora, vamos explorar o efeito das covariáveis usando gráficos.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1"><span class="kw">plot</span>(<span class="kw">allEffects</span>(ajuste1))</a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>Cada gráfico apresenta a estimativa do total de vendas (e bandas de confiança 95%) para os valores de uma variável (representados no eixo horizontal) fixando as demais variáveis na média.</p>
<div id="section" class="section level154">
<p></p>
<p>Diagnóstico - primeiramente vamos extrair os diferentes tipos de resíduos.</p>
<p>Resíduos ordinários.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1">e1 &lt;-<span class="st"> </span><span class="kw">resid</span>(ajuste1)</a>
<a class="sourceLine" id="cb41-2" data-line-number="2"><span class="kw">head</span>(e1, <span class="dt">n =</span> <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##        1        2        3        4        5        6        7        8 
##  1169.56  -629.76  -325.39 -3108.15   352.55  1638.99 -2963.68 -2190.74 
##        9       10 
##  1999.96 -2003.70</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" data-line-number="1">sigma &lt;-<span class="st"> </span><span class="kw">summary</span>(ajuste1)<span class="op">$</span>sigma</a></code></pre></div>
<p>Extraindo (a raiz do) quadrado médio de resíduos produzido pelo ajuste.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1">d1 &lt;-<span class="st"> </span>e1<span class="op">/</span>sigma</a>
<a class="sourceLine" id="cb44-2" data-line-number="2"><span class="kw">head</span>(d1, <span class="dt">n =</span> <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##        1        2        3        4        5        6        7        8 
##  0.61306 -0.33011 -0.17056 -1.62922  0.18480  0.85912 -1.55350 -1.14834 
##        9       10 
##  1.04834 -1.05030</code></pre>
<p>Resíduos padronizados.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1">r1 &lt;-<span class="st"> </span><span class="kw">rstandard</span>(ajuste1)</a>
<a class="sourceLine" id="cb46-2" data-line-number="2"><span class="kw">head</span>(r1, <span class="dt">n =</span> <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##        1        2        3        4        5        6        7        8 
##  0.62348 -0.33627 -0.17283 -1.64473  0.18894  0.88527 -1.57054 -1.15854 
##        9       10 
##  1.05582 -1.06069</code></pre>
<p>Resíduos studentizados (internamente).</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1">r2 &lt;-<span class="st"> </span><span class="kw">rstudent</span>(ajuste1)</a>
<a class="sourceLine" id="cb48-2" data-line-number="2"><span class="kw">head</span>(r2, <span class="dt">n =</span> <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##        1        2        3        4        5        6        7        8 
##  0.62250 -0.33550 -0.17240 -1.65201  0.18847  0.88478 -1.57651 -1.15956 
##        9       10 
##  1.05613 -1.06103</code></pre>
<p>Resíduos studentizados (externamente).</p>
<p>Veja a documentação da função rstudent para relembrar a diferença desses dois tipos de resíduos.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" data-line-number="1"><span class="kw">plot</span>(r1,r2) </a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Repare que há pouca diferença nos valores dos dois tipos de resíduos.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1">fit &lt;-<span class="st"> </span><span class="kw">fitted</span>(ajuste1)</a></code></pre></div>
<p>Daqui por diante, vamos usar apenas os resíduos studentizados internamente.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb52-2" data-line-number="2"><span class="kw">plot</span>(ajuste1, <span class="dt">which =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="dt">cex =</span> <span class="fl">1.2</span>, <span class="dt">pch =</span> <span class="dv">20</span>) </a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>Conjunto de gráficos de diagnóstico padrão do R. O gráfico do canto superior esquerdo é de resíduos ordinários versus valores ajustados. Repare que os resíduos estão dispersos aleatoriamente, sem valores extremos ou padrões não aleatórios. Vamos fazer um gráfico semelhante, mas baseado nos resíduos studentizados:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">cex=</span><span class="fl">1.4</span>,<span class="dt">las=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb53-2" data-line-number="2"></a>
<a class="sourceLine" id="cb53-3" data-line-number="3"><span class="kw">plot</span>(fit, r1, <span class="dt">xlab=</span><span class="st">&#39;Valores ajustados&#39;</span>, <span class="dt">ylab=</span><span class="st">&#39;Resíduos studentizados&#39;</span>, <span class="dt">pch=</span><span class="dv">20</span>)</a>
<a class="sourceLine" id="cb53-4" data-line-number="4"></a>
<a class="sourceLine" id="cb53-5" data-line-number="5"><span class="kw">identify</span>(fit,r1,<span class="kw">rownames</span>(vendas)) <span class="co"># Vamos identificar a observação com resíduo superior a 3</span></a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<pre><code>## integer(0)</code></pre>
<p>A observação com resíduo superior a 3 está na linha 195. Vamos avaliá-la:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" data-line-number="1">vendas[<span class="dv">195</span>,]</a></code></pre></div>
<pre><code>##     Tempo Idade Estudo Populacao Venda
## 195    14    44     14     11995 20775</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" data-line-number="1"><span class="kw">summary</span>(vendas)</a></code></pre></div>
<pre><code>##      Tempo           Idade          Estudo        Populacao    
##  Min.   : 0.00   Min.   :23.0   Min.   : 4.00   Min.   :  128  
##  1st Qu.: 7.00   1st Qu.:35.0   1st Qu.: 6.00   1st Qu.: 7595  
##  Median :10.00   Median :40.0   Median : 8.00   Median :10399  
##  Mean   : 9.85   Mean   :39.6   Mean   : 8.65   Mean   :10143  
##  3rd Qu.:13.00   3rd Qu.:44.0   3rd Qu.:11.00   3rd Qu.:12618  
##  Max.   :20.00   Max.   :57.0   Max.   :17.00   Max.   :21203  
##      Venda      
##  Min.   : 4008  
##  1st Qu.:10508  
##  Median :12708  
##  Mean   :12597  
##  3rd Qu.:14584  
##  Max.   :20775</code></pre>
<p>Essa é a vendedora com maior total em vendas. Repare que, embora ela tenha 14 anos de experiência em vendas, atende uma Populacao pequena, de tamanho 11995. Logo, seu desempenho real foi bem superior ao esperado.</p>
<p>Voltando aos gráficos do R. O gráfico do canto superior direito é o gráfico probabilístico normal. Repare um leve afastamento da distribuição normal à esquerda (para valores negativos). Isso não é preocupante, mas vamos fazer um teste para checar a suposição de normalidade.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" data-line-number="1"><span class="kw">shapiro.test</span>(r1) </a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  r1
## W = 0.993, p-value = 0.45</code></pre>
<p>A hipótese nula do teste de Shapiro-Wilks é a hipótese de normalidade. Repare que não se tem evidência significativa contra essa hipótese. Logo, a normalidade dos resíduos está verificada.</p>
<p>O gráfico do canto inferior esquerdo é o gráfico da raiz quadrada dos resíduos studentizados (em módulo) versus valores ajustados. Serve para avaliar a suposição de variância constante (dentre outros).</p>
<p>Não há indícios de heterocedasticidade (variância não constante). Repare que no gráfico são assinalados os maiores resíduos, o que já havíamos identificado anteriormente.</p>
<p>Podemos usar o teste de Breusch-Pagan para testar a hipótese de variância constante para os erros. A hipótese nula é a de variância constante e o teste baseia-se na distribuição qui-quadrado. Pode-se testar a homogeneidade de variâncias quanto à média ou a algum termo específico do modelo.</p>
<p>No R - função ncvTest, pacote car.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" data-line-number="1"><span class="kw">ncvTest</span>(ajuste1) </a></code></pre></div>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 0.26254, Df = 1, p = 0.608</code></pre>
<p>Não há evidência de que a variância dos erros varie conforme a média (p=0,608)</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" data-line-number="1"><span class="kw">ncvTest</span>(ajuste1,<span class="op">~</span><span class="st">&#39;Populacao&#39;</span>) </a></code></pre></div>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ Populacao 
## Chisquare = 0.33124, Df = 1, p = 0.565</code></pre>
<p>Não há evidência de que a variância dos erros varie conforme o tamanho da Populacao atendida (p=0,564)</p>
<p>Falaremos sobre o gráfico do canto inferior direito mais adiante. Vamos construir mais alguns gráficos.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" data-line-number="1"><span class="kw">qqPlot</span>(ajuste1, <span class="dt">main=</span><span class="st">&quot;QQ Plot&quot;</span>,<span class="dt">id.n=</span><span class="dv">3</span>) </a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<pre><code>## [1] 170 195</code></pre>
<p>Gráfico quantil-quantil dos resíduos studentizados vs quantis teóricos da distribuição t-Student com envelopes simulados. Nesse tipo de gráfico, espera-se que os pontos, que correspondem aos resíduos, estejam dispersos em torno da reta identidade, entre os limites do envelope. Nota-se um pequeno afastamento na cauda inferior, com um ponto externo ao envelope.</p>
<p>Gráfico de resíduos versus variável adicionada no modelo.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">cex=</span><span class="fl">1.2</span>,<span class="dt">las=</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb67-2" data-line-number="2"><span class="kw">plot</span>(vendas<span class="op">$</span>Populacao, r1, <span class="dt">xlab=</span><span class="st">&#39;Populacao atendida&#39;</span>, <span class="dt">ylab=</span><span class="st">&#39;Resíduos studentizados&#39;</span>, <span class="dt">pch=</span><span class="dv">20</span>)</a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" data-line-number="1"><span class="kw">plot</span>(vendas<span class="op">$</span>Estudo, r1, <span class="dt">xlab=</span><span class="st">&#39;Anos de estudo&#39;</span>, <span class="dt">ylab=</span><span class="st">&#39;Resíduos studentizados&#39;</span>, <span class="dt">pch=</span><span class="dv">20</span>)</a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-37-2.png" width="672" /></p>
<p>A ausência de padrões nos dois gráficos indica que não há a necessidade de considerar a inclusão dessas variáveis ao modelo em alguma outra escala.</p>
<p>Gráfico de resíduos versus variáveis não inseridas ao modelo.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" data-line-number="1">ajuste12 &lt;-<span class="st"> </span><span class="kw">update</span>(ajuste1,<span class="op">~</span><span class="st"> </span>.<span class="op">-</span>Populacao) </a></code></pre></div>
<p>Ajustando o modelo sem o efeito de Populacao.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" data-line-number="1"><span class="kw">plot</span>(vendas<span class="op">$</span>Populacao, <span class="kw">rstudent</span>(ajuste12),<span class="dt">xlab=</span><span class="st">&#39;Populacao atendida&#39;</span>,</a>
<a class="sourceLine" id="cb70-2" data-line-number="2">     <span class="dt">ylab=</span><span class="st">&#39;Resíduos studentizados&#39;</span>,<span class="dt">pch=</span><span class="dv">20</span>)</a>
<a class="sourceLine" id="cb70-3" data-line-number="3"></a>
<a class="sourceLine" id="cb70-4" data-line-number="4"><span class="kw">lines</span>(<span class="kw">lowess</span>(vendas<span class="op">$</span>Populacao, <span class="kw">rstudent</span>(ajuste12)),<span class="dt">col=</span><span class="st">&#39;red&#39;</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>A relação linear entre resíduos e Populacao atendida indica a necessidade da inclusão dessa variável ao modelo. Adicionalmente, indica o efeito linear dessa variável no total de vendas.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" data-line-number="1">ajuste13=<span class="kw">update</span>(ajuste1,<span class="op">~</span>.<span class="op">-</span>Estudo) </a></code></pre></div>
<p>Ajustando o modelo sem o efeito de estudo.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" data-line-number="1"><span class="kw">plot</span>(vendas<span class="op">$</span>Estudo,<span class="kw">rstudent</span>(ajuste12),<span class="dt">xlab=</span><span class="st">&#39;Anos de estudo&#39;</span>,</a>
<a class="sourceLine" id="cb72-2" data-line-number="2">     <span class="dt">ylab=</span><span class="st">&#39;Resíduos studentizados&#39;</span>,<span class="dt">pch=</span><span class="dv">20</span>)</a>
<a class="sourceLine" id="cb72-3" data-line-number="3"><span class="kw">lines</span>(<span class="kw">lowess</span>(vendas<span class="op">$</span>Estudo,<span class="kw">rstudent</span>(ajuste12)),<span class="dt">col=</span><span class="st">&#39;red&#39;</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>A ausência de relação entre os resíduos e anos de estudo fornece evidencia<br />
de não ser necessária a inclusão dessa variável ao modelo.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" data-line-number="1"><span class="kw">require</span>(car)</a>
<a class="sourceLine" id="cb73-2" data-line-number="2"><span class="kw">crPlots</span>(ajuste1) </a></code></pre></div>
<p><img src="venda_cos_mod2_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>Os gráficos de resíduos parciais indicam a relação entre resíduos parciais e as variáveis “anos de estudo” e “Populacao atendida”. Aparentemente, as relações são lineares, indicando a forma como as variáveis devem ser inseridas no modelo.</p>
<p>Agora, vamos calcular medidas de influência com o objetivo de identificar possíveis outliers.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" data-line-number="1">matinf &lt;-<span class="st"> </span><span class="kw">influence.measures</span>(ajuste1) </a></code></pre></div>
<p>matinf armazena os valores de diversas medidas de influência vistas em aula, como DFBETAs, DFFIT, leverage.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" data-line-number="1"><span class="kw">summary</span>(matinf) </a></code></pre></div>
<pre><code>## Potentially influential observations of
##   lm(formula = Venda ~ ., data = vendas) :
## 
##     dfb.1_ dfb.Temp dfb.Idad dfb.Estd dfb.Pplc dffit cov.r   cook.d
## 27   0.02   0.04    -0.04     0.02     0.00     0.06  1.08_*  0.00 
## 66  -0.01   0.00     0.00    -0.01     0.01     0.01  1.08_*  0.00 
## 69  -0.01   0.00     0.00     0.00     0.01     0.01  1.11_*  0.00 
## 74   0.28   0.12    -0.33     0.20    -0.17     0.45  0.91_*  0.04 
## 82  -0.04  -0.27     0.09     0.13    -0.03    -0.32  0.91_*  0.02 
## 89  -0.09  -0.01     0.06     0.03     0.07     0.11  1.08_*  0.00 
## 136  0.00   0.01    -0.02     0.01     0.01    -0.03  1.08_*  0.00 
## 143  0.00  -0.01     0.01    -0.01     0.01    -0.02  1.08_*  0.00 
## 170  0.09  -0.18     0.06    -0.17     0.10     0.39  0.89_*  0.03 
## 173  0.03   0.02     0.00    -0.03    -0.05     0.06  1.08_*  0.00 
## 195 -0.21   0.05     0.01     0.32     0.14     0.47  0.81_*  0.04 
##     hat    
## 27   0.05  
## 66   0.05  
## 69   0.08_*
## 74   0.03  
## 82   0.02  
## 89   0.06  
## 136  0.05  
## 143  0.05  
## 170  0.02  
## 173  0.05  
## 195  0.02</code></pre>
<p>Aplicando o summary, o R destaca as observações com valores que ultrapassam o ponto de corte para ao menos uma das medidas. Repare que exceto uma das observações destacadas, todas as demais tem valor acima do ponto de corte para a estatística COVRATIO. Repare que a observação que produz menor valor do COVRATIO é a 195 que, se você lembrar, é a vendedora com maior total de vendas (volte alguns códigos atrás).</p>
<p>A observação 69 é marcada como tendo elevado leverage, configurando um ponto de alavancagem. Vamos ver quem é ela.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" data-line-number="1"><span class="kw">summary</span>(vendas)</a></code></pre></div>
<pre><code>##      Tempo           Idade          Estudo        Populacao    
##  Min.   : 0.00   Min.   :23.0   Min.   : 4.00   Min.   :  128  
##  1st Qu.: 7.00   1st Qu.:35.0   1st Qu.: 6.00   1st Qu.: 7595  
##  Median :10.00   Median :40.0   Median : 8.00   Median :10399  
##  Mean   : 9.85   Mean   :39.6   Mean   : 8.65   Mean   :10143  
##  3rd Qu.:13.00   3rd Qu.:44.0   3rd Qu.:11.00   3rd Qu.:12618  
##  Max.   :20.00   Max.   :57.0   Max.   :17.00   Max.   :21203  
##      Venda      
##  Min.   : 4008  
##  1st Qu.:10508  
##  Median :12708  
##  Mean   :12597  
##  3rd Qu.:14584  
##  Max.   :20775</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" data-line-number="1">vendas[<span class="dv">69</span>,] </a></code></pre></div>
<pre><code>##    Tempo Idade Estudo Populacao Venda
## 69    11    53      6     21203 19867</code></pre>
<p>Repare que essa vendedora atende à região com maior Populacao. Adicionalmente, é uma das vendedoras com maior idade e com menor tempo de estudo.</p>
<p>Vamos verificar o impacto (conjunto) das observações 69 e 195 no modelo, ajustando um novo modelo sem essas observações.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" data-line-number="1">ajuste2 &lt;-<span class="st"> </span><span class="kw">update</span>(ajuste1, <span class="dt">subset =</span> <span class="op">-</span><span class="kw">c</span>(<span class="dv">69</span>,<span class="dv">195</span>)) </a></code></pre></div>
<p>A função update permite o ajuste de um novo modelo, atualizando o anterior. Repare que a atualização corresponde a definição de um subconjunto dos dados.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" data-line-number="1"><span class="kw">compareCoefs</span>(ajuste1, ajuste2) </a></code></pre></div>
<pre><code>## Calls:
## 1: lm(formula = Venda ~ ., data = vendas)
## 2: lm(formula = Venda ~ ., data = vendas, subset = -c(69, 195))
## 
##             Model 1 Model 2
## (Intercept)    3204    3396
## SE              901     901
##                            
## Tempo         174.4   172.6
## SE             40.9    40.1
##                            
## Idade          18.0    17.5
## SE             22.4    22.2
##                            
## Estudo         67.8    52.8
## SE             48.0    47.4
##                            
## Populacao    0.6286  0.6232
## SE           0.0373  0.0374
## </code></pre>
<p>A função compareCoefs, do pacote car, dispõe lado a lado as estimativas e erros padrões de dois modelos. Repare que a alteração mais substancial nos dois ajustes se refere à estimativa do efeito de ajuste (de 67,8 para 52,8). No entanto, nos dois ajustes o efeito de anos de estudo é não significativo. Portanto, as conclusões para os dois modelos são semelhantes.</p>
<!-- Mais um pouco de diagnóstico.  -->
<!-- ```{r warning = F} -->
<!-- influenceIndexPlot(ajuste1, vars=c('Studentized','Cook','Hat'), id.n=3, cex = 1.4) -->
<!-- ``` -->
<!-- Seleção de covariáveis. -->
<!-- ```{r} -->
<!-- allsub <- regsubsets(Venda~., data=vendas) -->
<!-- ``` -->
<!-- A função regsubsets determina, para cada tamanho de modelo (número de  -->
<!-- variáveis incluídas), o melhor modelo. -->
<!-- ```{r} -->
<!-- plot(allsub) -->
<!-- s1 <- summary(allsub)  -->
<!-- s1 -->
<!-- ``` -->
<!-- Resumo do processo. Verifique que o melhor modelo com uma variável  -->
<!-- tem a variável Populacao, com duas Populacao e Tempo... -->
<!-- Agora, vamos extrair algumas medidas de qualidade de ajuste desses modelos: -->
<!-- ```{r} -->
<!-- s1$rsq # Coeficientes de determinação; -->
<!-- s1$adjr2 # Coeficientes de determinação ajustados; -->
<!-- s1$cp # CP de Mallows; -->
<!-- s1$bic # Critério de informação de Schwartz. -->
<!-- ``` -->
<!-- Vamos observar os resultados num gráfico: -->
<!-- ```{r} -->
<!-- subsets(allsub, statistic='adjr2') -->
<!-- ``` -->
<!-- Repare que os melhores modelos com duas, três e quatro variáveis têm  -->
<!-- coeficientes de determinação bastante próximos. Nesse caso, a opção  -->
<!-- poderia ser pelo modelo mais simples, no caso o modelo com duas variáveis  -->
<!-- (Tempo de experiência e Populacao atendida). -->
<!-- Agora, só para praticar, usando algoritmos do tipo stepwise. -->
<!-- Usando o método backward. -->
<!-- ```{r} -->
<!-- selb <- step(ajuste1, direction = 'backward') -->
<!-- summary(selb) -->
<!-- ``` -->
<!-- Usando o método forward -->
<!-- ```{r} -->
<!-- self <- step(ajuste1, direction = 'forward') -->
<!-- summary(self) -->
<!-- ``` -->
<!-- Usando o método forward -->
<!-- ```{r} -->
<!-- selbf <- step(ajuste1, direction = 'both') -->
<!-- summary(selbf) -->
<!-- ``` -->
<!-- Avalie os modelos resultantes das aplicações dos três métodos. -->
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4,h5",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
